import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { FlatList } from 'react-native';
import { blockService } from '../../services/blockService';
import { dbService } from '../../services/firebaseService';
import { COLORS } from '../../theme/COLORS';

const BlockedUsersScreen=()=>{const[users,setUsers]=useState([]);const[loading,setLoading]=useState(true);const load=()=>blockService.getBlockedIds().then(ids=>Promise.all(ids.map(id=>dbService.getUserProfile(id)))).then(items=>setUsers(items.filter(Boolean))).catch(()=>Alert.alert('Unable to load','Blocked users could not be loaded.')).finally(()=>setLoading(false));useEffect(load,[]);if(loading)return <ActivityIndicator style={{marginTop:80}} color={COLORS.primary}/>;return <FlatList style={styles.container} contentContainerStyle={styles.content} data={users} keyExtractor={item=>item.uid} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No blocked users</Text><Text style={styles.muted}>People you block will appear here.</Text></View>} renderItem={({item})=><View style={styles.row}>{item.profilePic?<Image source={{uri:item.profilePic}} style={styles.avatar}/>:<View style={[styles.avatar,styles.placeholder]}><Text>{item.username?.[0]||'A'}</Text></View>}<Text style={styles.name}>{item.username||'Amira user'}</Text><TouchableOpacity style={styles.button} onPress={async()=>{await blockService.unblock(item.uid);setUsers(current=>current.filter(user=>user.uid!==item.uid));}}><Text style={styles.buttonText}>Unblock</Text></TouchableOpacity></View>}/>};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F7F9'},content:{padding:14,flexGrow:1},row:{backgroundColor:'white',borderRadius:17,padding:12,marginBottom:9,flexDirection:'row',alignItems:'center',gap:11},avatar:{width:50,height:50,borderRadius:25},placeholder:{backgroundColor:'#E9D5FF',alignItems:'center',justifyContent:'center'},name:{flex:1,fontSize:16,fontWeight:'800',color:COLORS.text},button:{borderWidth:1,borderColor:COLORS.primary,borderRadius:18,paddingHorizontal:13,paddingVertical:8},buttonText:{color:COLORS.primary,fontWeight:'800'},empty:{alignItems:'center',marginTop:100},emptyTitle:{fontSize:20,fontWeight:'900',color:COLORS.text},muted:{color:COLORS.textSecondary,marginTop:7}});export default BlockedUsersScreen;
