import React, { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Image, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { MessageCircle, Search, UserMinus } from 'lucide-react-native';
import { COLORS } from '../../theme/COLORS';
import { discoveryService } from '../../services/discoveryService';
import { followService } from '../../services/followService';

const FollowingScreen=({navigation})=>{const[hosts,setHosts]=useState([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const load=useCallback(async()=>{setLoading(true);try{setHosts(await discoveryService.getFollowingHosts());}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{load();},[load]));const visible=useMemo(()=>hosts.filter((host)=>[host.username,host.countryName,...(host.hostProfile?.interests||[])].join(' ').toLowerCase().includes(search.trim().toLowerCase())),[hosts,search]);const unfollow=async(host)=>{if(host.isDemo){setHosts((items)=>items.filter((item)=>item.uid!==host.uid));return;}await followService.unfollowHost(host.uid);setHosts((items)=>items.filter((item)=>item.uid!==host.uid));};return <View style={styles.container}><View style={styles.search}><Search color={COLORS.textSecondary} size={18}/><TextInput style={{flex:1}} value={search} onChangeText={setSearch} placeholder="Search people you follow"/></View>{loading?<ActivityIndicator style={{marginTop:80}} color={COLORS.primary}/>:<FlatList data={visible} keyExtractor={(item)=>item.uid} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>You are not following any approved hosts yet.</Text>} renderItem={({item})=><TouchableOpacity style={styles.item} onPress={()=>navigation.navigate('UserProfile',{userId:item.uid,demoHost:item.isDemo?item:undefined})}>{item.profilePic?<Image source={{uri:item.profilePic}} style={styles.avatar}/>:<View style={styles.avatar}/>}<View style={{flex:1}}><Text style={styles.name}>{item.username}{item.isDemo?' · Demo':''}</Text><Text style={styles.meta}>{item.countryName} · {item.hostStatus?.availability}</Text></View><TouchableOpacity style={styles.unfollow} onPress={()=>navigation.navigate('ChatDetail',{userId:item.uid,name:item.username})}><MessageCircle color={COLORS.primary} size={18}/><Text style={styles.unfollowText}>Message</Text></TouchableOpacity><TouchableOpacity style={styles.unfollow} onPress={()=>unfollow(item)}><UserMinus color={COLORS.primary} size={18}/><Text style={styles.unfollowText}>Unfollow</Text></TouchableOpacity></TouchableOpacity>}/>}</View>};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F7F9',padding:14},search:{height:50,borderRadius:16,backgroundColor:'white',paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:8,marginBottom:12},list:{paddingBottom:40},item:{backgroundColor:'white',padding:12,borderRadius:17,marginBottom:9,flexDirection:'row',alignItems:'center',gap:11},avatar:{width:54,height:54,borderRadius:27,backgroundColor:'#DDD'},name:{fontSize:16,fontWeight:'900',color:COLORS.text},meta:{color:COLORS.textSecondary,fontSize:12,marginTop:3,textTransform:'capitalize'},unfollow:{alignItems:'center'},unfollowText:{color:COLORS.primary,fontSize:9,fontWeight:'800',marginTop:2},empty:{textAlign:'center',color:COLORS.textSecondary,marginTop:90,lineHeight:21}});export default FollowingScreen;
