import React, { useCallback, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect, useIsFocused } from '@react-navigation/native';
import { SlidersHorizontal } from 'lucide-react-native';
import { COLORS } from '../../theme/COLORS';
import { discoveryService } from '../../services/discoveryService';
import HostCard from '../../components/HostCard';
import DiscoveryFilterModal from '../../components/DiscoveryFilterModal';
import {useDiscoveryFilters,EMPTY_DISCOVERY_FILTERS} from '../../hooks/useDiscoveryFilters';
import {filterDiscoveryHosts,discoveryFilterCount} from '../../utils/discoveryFilters';
import { startVideoCall } from '../../services/callNavigationService';
import SponsoredCallInviteBanner from '../../components/SponsoredCallInviteBanner';

const TABS = ['For You', 'New', 'Following'];
const HomeScreen = ({ navigation }) => {
  const request=useRef(0);
  const [visibleIds,setVisibleIds]=useState(new Set());
  const viewability=useRef({itemVisiblePercentThreshold:50}).current;
  const onViewableItemsChanged=useRef(({viewableItems})=>setVisibleIds(new Set(viewableItems.map(entry=>entry.item.uid)))).current;
  const [activeTab,setActiveTab]=useState('For You'); const [hosts,setHosts]=useState([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [filters,setFilters]=useDiscoveryFilters(); const focused=useIsFocused(); const [filterOpen,setFilterOpen]=useState(false);
  const loadHosts=useCallback(async()=>{const version=++request.current;setLoading(true);setError('');try{const result=activeTab==='Following'?await discoveryService.getFollowingHosts():activeTab==='New'?await discoveryService.getNewHosts():await discoveryService.getApprovedHosts();if(version===request.current)setHosts(result);}catch(e){if(version===request.current){setHosts([]);setError('Hosts could not be loaded. Try again.');}}finally{if(version===request.current)setLoading(false);}},[activeTab]);
  useFocusEffect(useCallback(()=>{loadHosts();return()=>{request.current++;};},[loadHosts]));
  const visibleHosts=useMemo(()=>filterDiscoveryHosts(hosts,filters),[hosts,filters]);
  const activeFilterCount=discoveryFilterCount(filters);
  const storyHosts=visibleHosts.filter((host)=>host.hasActiveStory&&host.stories?.length);
  const openProfile=(host)=>navigation.navigate('UserProfile',{userId:host.uid});
  const openStory=(host)=>navigation.navigate('StoryViewer',{stories:host.stories,userName:host.username});
  const empty=error||(activeTab==='Following'?'Follow approved hosts to browse them here.':activeTab==='New'?'No hosts were approved in the last 14 days.':'No Hosts match your filters right now.');
  return <View style={styles.container}><View style={styles.header}><Text style={styles.title}>Discover</Text><View style={styles.tabs}>{TABS.map((tab)=><TouchableOpacity key={tab} style={[styles.tab,activeTab===tab&&styles.activeTab]} onPress={()=>setActiveTab(tab)}><Text style={[styles.tabText,activeTab===tab&&styles.activeTabText]}>{tab.toUpperCase()}</Text></TouchableOpacity>)}<TouchableOpacity style={[styles.filter,activeFilterCount&&styles.filterActive]} onPress={()=>setFilterOpen(true)}><SlidersHorizontal color={activeFilterCount?'white':COLORS.text} size={19}/>{activeFilterCount>0&&<View style={styles.count}><Text style={styles.countText}>{activeFilterCount}</Text></View>}</TouchableOpacity></View>{activeFilterCount>0&&<Text style={styles.filtered}>Filters applied · tap the filter icon to edit or clear</Text>}</View><SponsoredCallInviteBanner navigation={navigation}/>
    {loading?<View style={styles.center}><ActivityIndicator color={COLORS.primary} size="large"/></View>:<FlatList onViewableItemsChanged={onViewableItemsChanged} viewabilityConfig={viewability} data={visibleHosts} numColumns={2} columnWrapperStyle={styles.columns} keyExtractor={(item)=>item.uid} contentContainerStyle={styles.list} refreshing={loading} onRefresh={loadHosts} ListHeaderComponent={storyHosts.length?<View style={styles.storyBlock}><Text style={styles.storyTitle}>Stories</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}>{storyHosts.map((host)=><TouchableOpacity key={host.uid} style={styles.story} onPress={()=>openStory(host)}><View style={styles.storyRing}><Image source={{uri:host.storyThumbnail||host.profilePic}} style={styles.storyImage}/></View><Text style={styles.storyName} numberOfLines={1}>{host.username}</Text></TouchableOpacity>)}</ScrollView></View>:null} renderItem={({item})=><HostCard host={item} autoCycle={focused&&visibleIds.has(item.uid)} onPress={()=>openProfile(item)} onStoryPress={()=>openStory(item)} onCallPress={()=>startVideoCall({navigation,creator:item})}/>} ListEmptyComponent={<View style={styles.empty}><SlidersHorizontal color={COLORS.primary} size={38}/><Text style={styles.emptyTitle}>Nothing to show</Text><Text style={styles.emptyText}>{empty}</Text>{error&&<TouchableOpacity onPress={loadHosts}><Text style={styles.clear}>Try Again</Text></TouchableOpacity>}{activeFilterCount>0&&<TouchableOpacity onPress={()=>setFilters(EMPTY_DISCOVERY_FILTERS)}><Text style={styles.clear}>Clear filters</Text></TouchableOpacity>}</View>}/>}<DiscoveryFilterModal visible={filterOpen} value={filters} onClose={()=>setFilterOpen(false)} onApply={setFilters} languages={[...new Set(hosts.flatMap(host=>host.languages||[]))].sort()}/></View>;
};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F7F9'},header:{backgroundColor:'white',paddingTop:54,paddingHorizontal:14,paddingBottom:12},title:{fontSize:29,fontWeight:'900',color:COLORS.text},tabs:{flexDirection:'row',gap:5,marginTop:17,alignItems:'center'},tab:{flex:1,paddingVertical:9,borderRadius:16,backgroundColor:'#F1F1F4',alignItems:'center'},activeTab:{backgroundColor:COLORS.primary},tabText:{fontSize:10,fontWeight:'900',color:COLORS.textSecondary},activeTabText:{color:'white'},filter:{width:39,height:39,borderRadius:14,backgroundColor:'#F1F1F4',alignItems:'center',justifyContent:'center'},filterActive:{backgroundColor:COLORS.primary},count:{position:'absolute',right:-3,top:-5,minWidth:16,height:16,borderRadius:8,backgroundColor:'#111',alignItems:'center',justifyContent:'center'},countText:{color:'white',fontSize:9,fontWeight:'900'},filtered:{color:COLORS.textSecondary,fontSize:11,marginTop:9},list:{padding:10,paddingBottom:100},columns:{justifyContent:'space-between'},center:{flex:1,alignItems:'center',justifyContent:'center'},storyBlock:{marginBottom:13},storyTitle:{fontSize:17,fontWeight:'900',margin:4,color:COLORS.text},story:{width:72,alignItems:'center',marginRight:5},storyRing:{width:59,height:59,borderRadius:30,borderWidth:3,borderColor:COLORS.primary,padding:3},storyImage:{width:'100%',height:'100%',borderRadius:25},storyName:{fontSize:11,fontWeight:'700',color:COLORS.text,marginTop:4,maxWidth:66},empty:{alignItems:'center',paddingHorizontal:30,marginTop:80,width:'100%'},emptyTitle:{fontSize:21,fontWeight:'900',color:COLORS.text,marginTop:12},emptyText:{color:COLORS.textSecondary,textAlign:'center',marginTop:7,lineHeight:20},clear:{color:COLORS.primary,fontWeight:'900',marginTop:14}});export default HomeScreen;
