import React, { useEffect, useState } from 'react';
import { ActivityIndicator, SafeAreaView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { ChevronLeft, Coins } from 'lucide-react-native';
import { COLORS } from '../../theme/COLORS';
import { creditWalletService } from '../../services/creditWalletService';

const RechargeHubScreen=({navigation})=>{const [wallet,setWallet]=useState(null);const [error,setError]=useState('');useEffect(()=>{creditWalletService.getWallet().then(setWallet).catch(()=>setError('Balance unavailable.'));},[]);return <SafeAreaView style={styles.container}><View style={styles.header}><TouchableOpacity onPress={()=>navigation.goBack()}><ChevronLeft color={COLORS.text} size={28}/></TouchableOpacity><Text style={styles.headerTitle}>Recharge</Text><View style={{width:28}}/></View><View style={styles.card}><Coins color="#FFD700" size={28}/><Text style={styles.label}>Available Credits</Text>{!wallet&&!error?<ActivityIndicator color={COLORS.primary}/>:<Text style={styles.value}>{wallet?.totalCredits?.toLocaleString()||'—'}</Text>}{error?<Text style={styles.error}>{error}</Text>:null}</View><View style={styles.notice}><Text style={styles.noticeTitle}>Recharge is not available yet</Text><Text style={styles.noticeText}>Credit packages and secure payment verification are being prepared. No payment can be started from this version.</Text></View></SafeAreaView>;};
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F0F2F5'},header:{height:60,flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingHorizontal:15,backgroundColor:COLORS.white},headerTitle:{fontSize:18,fontWeight:'bold'},card:{backgroundColor:COLORS.white,alignItems:'center',padding:30,margin:15,borderRadius:20},label:{color:COLORS.textSecondary,fontSize:14,marginTop:10},value:{fontSize:34,fontWeight:'bold',marginTop:8},notice:{backgroundColor:COLORS.white,marginHorizontal:15,padding:22,borderRadius:16},noticeTitle:{fontSize:18,fontWeight:'800',color:COLORS.text},noticeText:{color:COLORS.textSecondary,lineHeight:21,marginTop:8},error:{color:'#B42318',marginTop:8}});
export default RechargeHubScreen;
