import {useSessionGuard} from '../../hooks/useSessionGuard';
import React,{useCallback,useState} from 'react';
import {useFocusEffect} from '@react-navigation/native';
import {ActivityIndicator,ScrollView,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {Check,Crown} from 'lucide-react-native';
import {COLORS} from '../../theme/COLORS';
import {vipService} from '../../services/vipService';
const benefits=['Who Viewed Me identities','VIP Host Content access','Consumer photo sharing','Future paid messaging and video-call discounts','Better controlled rewards'];
export default function VIPStoreScreen(){const current=useSessionGuard();const [state,setState]=useState(null),[plans,setPlans]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);useFocusEffect(useCallback(()=>{let live=true;setError(false);setState(null);setPlans(null);Promise.all([vipService.state(),vipService.plans()]).then(([s,p])=>{if(live&&current()){setState(s);setPlans(p);}}).catch(()=>{if(live&&current()){setError(true);}});return()=>{live=false;};},[current,retry]));if(error)return <View style={styles.center}><Text>VIP information could not be loaded.</Text><TouchableOpacity onPress={()=>setRetry(value=>value+1)}><Text>Try again</Text></TouchableOpacity></View>;if(!state||!plans)return <View style={styles.center}><ActivityIndicator color={COLORS.primary}/></View>;return <ScrollView style={styles.container} contentContainerStyle={styles.content}><Crown color="#F59E0B" size={52}/><Text style={styles.title}>Amira VIP</Text>{state.active?<View style={styles.card}><Text style={styles.active}>VIP is active</Text><Text style={styles.body}>Plan: {state.planId}</Text><Text style={styles.body}>Expires {new Date(state.expiresAtMs).toLocaleString()}</Text><Text style={styles.note}>Fixed duration. No automatic renewal. Renewing or extending while active is unavailable.</Text></View>:<><Text style={styles.body}>One membership with fixed 3-day, 7-day, or 30-day purchase options.</Text><View style={styles.card}>{benefits.map(item=><View key={item} style={styles.row}><Check color={COLORS.primary} size={18}/><Text style={styles.benefit}>{item}</Text></View>)}</View>{!plans.available||!plans.plans.length?<Text style={styles.unavailable}>VIP purchasing is currently unavailable.</Text>:<Text style={styles.unavailable}>Checkout is not available yet.</Text>}</>}</ScrollView>;}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#F7F7F9'},content:{padding:22,alignItems:'center'},center:{flex:1,alignItems:'center',justifyContent:'center'},title:{fontSize:30,fontWeight:'900',color:COLORS.text,marginTop:12},card:{width:'100%',backgroundColor:'white',borderRadius:20,padding:20,marginTop:20},row:{flexDirection:'row',gap:10,marginBottom:13},benefit:{flex:1,color:COLORS.text},body:{color:COLORS.textSecondary,textAlign:'center',marginTop:10},note:{color:COLORS.textSecondary,lineHeight:21,marginTop:14},active:{fontSize:22,fontWeight:'900',color:COLORS.primary,textAlign:'center'},unavailable:{color:COLORS.textSecondary,fontWeight:'800',marginTop:24,textAlign:'center'}});
