const D=require('../callDomain');
const approved={role:'host',hostStatus:{isApproved:true,availability:'online'},hostProfile:{videoRateCredits:25}};
const start=(overrides={})=>D.validateStart({authUid:'consumer',creatorId:'creator',creator:approved,blocked:false,callerLock:false,creatorLock:false,...overrides});
describe('trusted call backend domain',()=>{
 test('1 unauthenticated call rejected',()=>expect(()=>D.requireAuthUid(null)).toThrow('unauthenticated'));
 test('2 self-call rejected',()=>expect(()=>start({creatorId:'consumer'})).toThrow('self-call'));
 test('3 unapproved creator rejected',()=>expect(()=>start({creator:{...approved,hostStatus:{isApproved:false,availability:'online'}}})).toThrow('unapproved'));
 test('4 unavailable creator rejected',()=>expect(()=>start({creator:{...approved,hostStatus:{isApproved:true,availability:'offline'}}})).toThrow('unavailable'));
 test('5 blocked relationship rejected',()=>expect(()=>start({blocked:true})).toThrow('blocked'));
 test('6 authoritative rate ignores client supplied rate',()=>expect(D.authoritativeRate(approved,{ratePerMinute:1})).toBe(25));
 test('7 call expiry uses centralized deadline',()=>expect(D.isExpired({expiresAtMs:1000},1001)).toBe(true));
 test('8 double acceptance rejected',()=>expect(()=>D.validateAcceptance({authUid:'creator',call:{receiverId:'creator',status:'connecting',expiresAtMs:9999},creator:approved,nowMs:1})).toThrow('not-ringable'));
 test('9 active-call concurrency rejected',()=>expect(()=>start({callerLock:{callId:'active'}})).toThrow('active-call-conflict'));
 test('10 RTC token is participant-only',()=>expect(()=>D.assertParticipant('stranger',{participantIds:['consumer','creator']})).toThrow('not-participant'));
 test('11 preview connection requires both RTC acknowledgements',()=>expect(D.shouldConnect({consumer:{remotePresent:true},creator:{remotePresent:true}},['consumer','creator'])).toBe(true));
 test.each(['rejected','failed'])('%s call cannot consume preview',status=>expect(D.shouldConnect({},['consumer','creator'])).toBe(false));
 test('14 second same-day preview rejected',()=>expect(D.previewEligible({dateKey:'2026-09-04',consumed:true},'2026-09-04')).toBe(false));
 test('15 next UTC day preview available',()=>expect(D.previewEligible({dateKey:'2026-09-03',consumed:true},'2026-09-04')).toBe(true));
 test('16 preview atomic concurrency sees consumed entitlement',()=>{const entitlement={dateKey:'2026-09-04',consumed:true,callId:'first'};expect(D.previewEligible(entitlement,'2026-09-04')).toBe(false);});
 test.each(['preview','awaiting_paid_confirmation'])('17 no billing in %s',billingMode=>expect(D.canSettle({status:'connected',billingMode})).toBe(false));
 test('18 10-second billing calculation',()=>expect(D.incrementCredits(30)).toBe(5));
 test('19 insufficient balance rejected',()=>expect(()=>D.debitWithoutDebt(4,5)).toThrow('insufficient'));
 test('20 wallet never becomes negative',()=>expect(D.debitWithoutDebt(5,5)).toBe(0));
 test('21 settlement idempotency key is deterministic',()=>expect(D.settlementId('call',2)).toBe(D.settlementId('call',2)));
 test('22 creator earnings uses same idempotency identity',()=>expect(D.settlementId('call',3)).toBe('call_3'));
 test('23 duplicate finalization is safe',()=>expect(D.idempotentFinalize('ended')).toBe(true));
 test('24 nonparticipant cannot manipulate call',()=>expect(()=>D.assertParticipant('x',{participantIds:['a','b']})).toThrow());
 test('25 client cannot choose billed amount',()=>expect(D.incrementCredits(D.authoritativeRate(approved,{billedAmount:999}))).toBe(5));
 test('unique RTC UIDs reject unsafe values',()=>expect(()=>D.sanitizeRtcUid(0)).toThrow('invalid-rtc-uid'));
 test('paid increments depend on authoritative elapsed time',()=>expect(D.payableIncrementCount({paidStartedAtMs:1000,nowMs:21000})).toBe(2));
});
