const {createConsumerLevels}=require('../consumerLevels');
const {createConsumerRewards}=require('../consumerRewards');
const docs=new Map();let queue;
const db={doc:path=>({path}),runTransaction:work=>{const run=queue.then(async()=>{const writes=[];const tx={get:async ref=>{if(writes.length)throw Error('Reads before writes');return {exists:docs.has(ref.path),data:()=>structuredClone(docs.get(ref.path))};},set:(ref,value,options)=>writes.push([ref.path,value,options]),create:(ref,value)=>{if(docs.has(ref.path))throw Error('duplicate');writes.push([ref.path,value]);}};const value=await work(tx);for(const [path,data,options] of writes)docs.set(path,options?.merge?{...docs.get(path),...data}:data);return value;});queue=run.catch(()=>{});return run;}};
const FieldValue={serverTimestamp:()=>Date.now()};class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
const levels=createConsumerLevels({db,FieldValue,HttpsError}),rewards=createConsumerRewards({db,FieldValue,HttpsError});
const TEST_CONFIG={version:'isolated-test',thresholds:Array.from({length:11},(_,level)=>level*100),milestones:{1:{freeMessages:2},2:{freeVideoSeconds:3,quickMatchCount:1}}};
beforeEach(()=>{queue=Promise.resolve();docs.clear();docs.set('users/c',{role:'consumer'});docs.set('users/p',{role:'host',hostStatus:{isApproved:false,verificationStatus:'pending'}});docs.set('users/h',{role:'host',hostStatus:{isApproved:true}});docs.set('consumerLevels/c',{lifetimeQualifyingPurchasedCredits:100});});
test('production absence ignores wallet/demo progress and exposes no milestone',async()=>{docs.get('users/c').wallet={creditBalance:100000};expect(await levels.snapshot('c')).toEqual({level:0,thresholdsConfigured:false,milestones:[]});await expect(levels.claim('c',{level:1})).rejects.toMatchObject({code:'failed-precondition'});});
test('configured test milestone below threshold cannot claim; at threshold is eligible',async()=>{docs.set('levelConfig/current',TEST_CONFIG);await expect(levels.claim('c',{level:2})).rejects.toMatchObject({code:'failed-precondition'});expect((await levels.snapshot('c')).milestones[0]).toMatchObject({eligible:true,claimed:false});});
test('concurrent claim grants once, higher Level and later reversal cannot replay it',async()=>{docs.set('levelConfig/current',TEST_CONFIG);const before=structuredClone(docs.get('consumerLevels/c'));await Promise.all([levels.claim('c',{level:1}),levels.claim('c',{level:1})]);expect(docs.get('consumerRewards/c').freeMessages).toBe(2);expect(docs.get('consumerLevels/c')).toEqual(before);docs.get('consumerLevels/c').lifetimeQualifyingPurchasedCredits=1000;expect((await levels.claim('c',{level:1})).idempotent).toBe(true);docs.get('consumerLevels/c').lifetimeQualifyingPurchasedCredits=0;expect((await levels.claim('c',{level:1})).idempotent).toBe(true);expect(docs.get('consumerRewards/c').freeMessages).toBe(2);expect([...docs.keys()].filter(path=>path.includes('messageTransactions'))).toHaveLength(1);});
test('Free Video and Quick Match grants cannot increase qualifying lifetime purchases',async()=>{docs.set('levelConfig/current',TEST_CONFIG);docs.get('consumerLevels/c').lifetimeQualifyingPurchasedCredits=200;await levels.claim('c',{level:2});expect(docs.get('consumerRewards/c')).toMatchObject({freeVideoSeconds:3,quickMatchCount:1});expect(docs.get('consumerLevels/c').lifetimeQualifyingPurchasedCredits).toBe(200);});
test('caller cannot redirect milestone, unconfigured Level has no claim, Host is ineligible',async()=>{docs.set('levelConfig/current',TEST_CONFIG);await expect(levels.claim('c',{level:1,uid:'other'})).rejects.toMatchObject({code:'invalid-argument'});await expect(levels.claim('p',{level:1})).rejects.toMatchObject({code:'failed-precondition'});await expect(levels.claim('h',{level:1})).rejects.toMatchObject({code:'permission-denied'});await expect(levels.snapshot('h')).rejects.toMatchObject({code:'permission-denied'});expect((await levels.snapshot('c')).milestones.map(item=>item.level)).toEqual([1,2]);});
test('own and approved Host public level exposes only badge, blocked/other Consumers denied',async()=>{docs.set('levelConfig/current',TEST_CONFIG);expect(await levels.publicLevel('h','c')).toEqual({level:1});await expect(levels.publicLevel('p','c')).rejects.toMatchObject({code:'permission-denied'});docs.set('users/c/blocked/h',{});await expect(levels.publicLevel('h','c')).rejects.toMatchObject({code:'permission-denied'});});
test('Daily Check-In uses UTC calendar consecutiveness, wraps and resets without changing Level',async()=>{jest.useFakeTimers();try{for(let day=1;day<=8;day++){jest.setSystemTime(new Date(Date.UTC(2026,8,day,23,59)));const result=await rewards.claim('c');expect(result.checkIn.lastRewardDay).toBe((day-1)%7+1);}jest.setSystemTime(new Date('2026-09-10T00:00:00Z'));expect((await rewards.claim('c')).checkIn.lastRewardDay).toBe(1);jest.setSystemTime(new Date('2026-09-15T00:00:00Z'));expect((await rewards.claim('c')).checkIn.lastRewardDay).toBe(1);expect(docs.get('consumerLevels/c').lifetimeQualifyingPurchasedCredits).toBe(100);}finally{jest.useRealTimers();}});
test('same-day duplicate and fake client clock cannot grant again; pending eligible and Host denied',async()=>{jest.useFakeTimers();try{jest.setSystemTime(new Date('2026-09-01T23:59:59Z'));await rewards.claim('c');const first=structuredClone(docs.get('consumerRewards/c'));expect((await rewards.claim('c',new Date('2030-01-01'))).alreadyClaimed).toBe(true);expect(docs.get('consumerRewards/c')).toEqual(first);jest.setSystemTime(new Date('2026-09-02T00:00:00Z'));expect((await rewards.claim('c')).checkIn.lastRewardDay).toBe(2);await expect(rewards.claim('p')).resolves.toHaveProperty('claimed',true);await expect(rewards.claim('h')).rejects.toMatchObject({code:'permission-denied'});}finally{jest.useRealTimers();}});
test('obsolete gifts in legacy trusted reward config never become grants',async()=>{docs.set('economyConfig/current',{dailyCheckInSchedule:Array(7).fill({promotionalGifts:{generic:1}})});const result=await rewards.claim('c');expect(result.reward).toEqual({freeMessages:0,freeVideoSeconds:0,quickMatchCount:0});expect(docs.get('consumerRewards/c')).not.toHaveProperty('promotionalGifts');});
