'use strict';
const D=require('../creditDomain');

const base={ownerUid:'consumer_1',purchasedCredits:20,bonusCredits:5,legacyCredits:10,unallocatedSpentCredits:0,totalBalance:35,accountingVersion:1};
test('new wallet classifies existing compatibility value as legacy',()=>expect(D.readWallet(null,'consumer_1',17)).toEqual({...base,purchasedCredits:0,bonusCredits:0,legacyCredits:17,totalBalance:17}));
test('trusted grants preserve provenance and total',()=>{expect(D.grant(base,'purchased',4)).toMatchObject({purchasedCredits:24,totalBalance:39});expect(D.grant(base,'bonus',4)).toMatchObject({bonusCredits:9,totalBalance:39});});
test('legacy compatibility increase never becomes purchased',()=>expect(D.readWallet(base,'consumer_1',40)).toMatchObject({purchasedCredits:20,bonusCredits:5,legacyCredits:15,totalBalance:40}));
test('ordinary compatibility spend reserves purchased provenance conservatively',()=>{const state=D.readWallet(base,'consumer_1',30);expect(state.unallocatedSpentCredits).toBe(5);expect(D.walletProjection(state)).toMatchObject({compositionResolved:false,purchasedCredits:null,bonusCredits:null,legacyCredits:null,giftEligiblePurchasedCredits:15,totalCredits:30});});
test('reversal removes purchase provenance without changing spendable total',()=>expect(D.reversePurchased(base,7)).toMatchObject({purchasedCredits:13,legacyCredits:17,totalBalance:35}));
test('reversal cannot make purchased credits negative',()=>expect(()=>D.reversePurchased(base,21)).toThrow(/below zero/));
test('wallet rejects broken invariants and unsafe numbers',()=>{expect(()=>D.readWallet({...base,totalBalance:99},'consumer_1',99)).toThrow(/invariant/);expect(()=>D.integer(1.2,'Credits')).toThrow();});
test('catalog is server authoritative and strictly shaped',()=>{expect(D.packageCatalog({starter:{credits:50,amountMinor:1000,currency:'ghs',label:'Starter'}}).starter).toMatchObject({credits:50,amountMinor:1000,currency:'GHS'});expect(()=>D.packageCatalog({bad:{credits:1,amountMinor:2,currency:'GHS',clientPrice:1}})).toThrow();});
test('provider proof must exactly match amount currency and reference',()=>{const attempt={reference:'ref_1',amountMinor:1000,currency:'GHS'},proof={success:true,reference:'ref_1',providerTransactionId:'txn_1',amountMinor:1000,currency:'ghs'};expect(D.providerVerification(proof,attempt)).toEqual({providerTransactionId:'txn_1'});expect(()=>D.providerVerification({...proof,amountMinor:999},attempt)).toThrow(/amount mismatch/);expect(()=>D.providerVerification({...proof,reference:'ref_2'},attempt)).toThrow(/reference mismatch/);});
test('history projection omits provider and internal payloads',()=>{const projected=D.safeLedgerEntry('entry_1',{type:'recharge',direction:'credit',credits:5,bucket:'purchased',status:'succeeded',providerPayload:{secret:true},ownerUid:'consumer_1'});expect(projected).not.toHaveProperty('providerPayload');expect(projected).not.toHaveProperty('ownerUid');});
test('generic debit records unresolved provenance and exact refund is its inverse',()=>{const spent=D.debitUnallocated(base,9);expect(spent).toMatchObject({purchasedCredits:20,bonusCredits:5,legacyCredits:10,unallocatedSpentCredits:9,totalBalance:26});expect(D.refundUnallocated(spent,9)).toEqual(base);});
test('generic debit cannot overdraw and refund cannot exceed recorded generic spend',()=>{expect(()=>D.debitUnallocated(base,36)).toThrow(/Insufficient/);expect(()=>D.refundUnallocated(base,1)).toThrow(/exceeds/);for(const value of [0,-1,1.5,Infinity,Number.MAX_SAFE_INTEGER+1])expect(()=>D.debitUnallocated(base,value)).toThrow();});
test.each([
 ['purchased only',{...base,purchasedCredits:20,bonusCredits:0,legacyCredits:0,totalBalance:20},20],
 ['bonus only',{...base,purchasedCredits:0,bonusCredits:20,legacyCredits:0,totalBalance:20},0],
 ['legacy only',{...base,purchasedCredits:0,bonusCredits:0,legacyCredits:20,totalBalance:20},0],
 ['purchased plus bonus',{...base,purchasedCredits:12,bonusCredits:20,legacyCredits:0,totalBalance:32},12],
 ['purchased plus legacy',{...base,purchasedCredits:12,bonusCredits:0,legacyCredits:20,totalBalance:32},12],
 ['all buckets',base,20],
 ['unresolved generic spending',{...base,unallocatedSpentCredits:8,totalBalance:27},12],
])('%s computes conservative Gift capacity',(_name,wallet,eligible)=>expect(D.giftEligiblePurchased(wallet)).toBe(eligible));
test('Gift debit touches purchased and total only',()=>expect(D.debitPurchasedGift(base,7)).toEqual({...base,purchasedCredits:13,totalBalance:28}));
test('high total cannot compensate for insufficient purchased provenance',()=>expect(()=>D.debitPurchasedGift({...base,purchasedCredits:5,bonusCredits:100,legacyCredits:100,totalBalance:200,unallocatedSpentCredits:5},1)).toThrow(/Insufficient/));
test('generic refund restores Gift capacity and reversal fails safely after Gift spend',()=>{const spent=D.debitUnallocated(base,9);expect(D.giftEligiblePurchased(spent)).toBe(11);expect(D.giftEligiblePurchased(D.refundUnallocated(spent,9))).toBe(20);const gifted=D.debitPurchasedGift(base,15);expect(()=>D.reversePurchased(gifted,10)).toThrow(/below zero/);});

const wallet=(p,b=0,l=0,u=0)=>({ownerUid:'consumer_1',purchasedCredits:p,bonusCredits:b,legacyCredits:l,unallocatedSpentCredits:u,totalBalance:p+b+l-u,accountingVersion:1});
const valid=state=>expect(state.totalBalance).toBe(state.purchasedCredits+state.bonusCredits+state.legacyCredits-state.unallocatedSpentCredits);
test('sequence 1: verified purchase then Gift',()=>{const bought=D.grant(wallet(0),'purchased',100),gifted=D.debitPurchasedGift(bought,30);expect(gifted).toEqual(wallet(70));valid(gifted);expect(D.giftEligiblePurchased(gifted)).toBe(70);});
test('sequence 2: purchase, generic spend, then Gift',()=>{const spent=D.debitUnallocated(wallet(100),40),gifted=D.debitPurchasedGift(spent,50);expect(gifted).toEqual(wallet(50,0,0,40));valid(gifted);expect(D.giftEligiblePurchased(gifted)).toBe(10);});
test('sequence 3: Gift, generic spend, then another Gift',()=>{let state=D.debitPurchasedGift(wallet(100),30);state=D.debitUnallocated(state,20);state=D.debitPurchasedGift(state,40);expect(state).toEqual(wallet(30,0,0,20));valid(state);expect(D.giftEligiblePurchased(state)).toBe(10);});
test('sequence 4: purchased plus bonus with interleaved Gift and generic spend',()=>{let state=D.debitPurchasedGift(wallet(100,50),30);state=D.debitUnallocated(state,40);state=D.debitPurchasedGift(state,20);expect(state).toEqual(wallet(50,50,0,40));valid(state);expect(D.giftEligiblePurchased(state)).toBe(10);});
test('sequence 5: purchased plus legacy, generic spend, then Gift',()=>{let state=D.debitUnallocated(wallet(100,0,50),60);state=D.debitPurchasedGift(state,30);expect(state).toEqual(wallet(70,0,50,60));valid(state);expect(D.giftEligiblePurchased(state)).toBe(10);});
test('sequence 6: generic spend and exact partial refund before Gift',()=>{let state=D.debitUnallocated(wallet(100),40);state=D.refundUnallocated(state,15);state=D.debitPurchasedGift(state,70);expect(state).toEqual(wallet(30,0,0,25));valid(state);expect(D.giftEligiblePurchased(state)).toBe(5);});
test('sequence 7: Gift, generic spend/refund, then Gift',()=>{let state=D.debitPurchasedGift(wallet(100),20);state=D.debitUnallocated(state,50);state=D.refundUnallocated(state,20);state=D.debitPurchasedGift(state,40);expect(state).toEqual(wallet(40,0,0,30));valid(state);expect(D.giftEligiblePurchased(state)).toBe(10);});
test('sequence 8: multiple Gifts and generic spends/refunds preserve the bound',()=>{let state=wallet(120,30,20);state=D.debitPurchasedGift(state,20);state=D.debitUnallocated(state,40);state=D.debitPurchasedGift(state,50);state=D.debitUnallocated(state,20);state=D.refundUnallocated(state,30);state=D.debitPurchasedGift(state,20);state=D.refundUnallocated(state,10);expect(state).toEqual(wallet(30,30,20,20));valid(state);expect(D.giftEligiblePurchased(state)).toBe(10);});
test('sequence 9: reversal after Gift fails safely or reclassifies only remaining purchased provenance',()=>{const gifted=D.debitPurchasedGift(wallet(100),60);expect(()=>D.reversePurchased(gifted,50)).toThrow(/below zero/);const reversed=D.reversePurchased(gifted,40);expect(reversed).toEqual(wallet(0,0,40));valid(reversed);expect(D.giftEligiblePurchased(reversed)).toBe(0);});
test('sequence 10: reversal followed by Gift checks never restores purchased eligibility',()=>{let state=D.debitUnallocated(wallet(100),20);state=D.reversePurchased(state,30);expect(D.giftEligiblePurchased(state)).toBe(50);state=D.debitPurchasedGift(state,50);state=D.reversePurchased(state,20);expect(state).toEqual(wallet(0,0,50,20));valid(state);expect(D.giftEligiblePurchased(state)).toBe(0);});
test('eligibility is the exact worst-case lower bound over every valid unresolved allocation',()=>{for(let p=0;p<=12;p++)for(let b=0;b<=8;b++)for(let l=0;l<=8;l++)for(let u=0;u<=p+b+l;u++){const state=wallet(p,b,l,u),possible=[];for(let fromP=0;fromP<=Math.min(p,u);fromP++)for(let fromB=0;fromB<=Math.min(b,u-fromP);fromB++){const fromL=u-fromP-fromB;if(fromL>=0&&fromL<=l)possible.push(p-fromP);}expect(possible.length).toBeGreaterThan(0);expect(D.giftEligiblePurchased(state)).toBe(Math.min(...possible));}});
test('each successful Gift reduces the proven lower bound exactly once',()=>{for(let p=1;p<=25;p++)for(let u=0;u<p;u++)for(let gift=1;gift<=p-u;gift++){const before=wallet(p,7,5,u),after=D.debitPurchasedGift(before,gift);valid(after);expect(D.giftEligiblePurchased(after)).toBe(D.giftEligiblePurchased(before)-gift);}});
