const {createHostDiscovery}=require('../hostDiscovery');
const {projectHost,controlledInterests,publicPhotos,ageFromDob}=require('../hostDiscoveryDomain');
const docs=new Map();let queue;
const snap=path=>({exists:docs.has(path),data:()=>structuredClone(docs.get(path))});
const db={doc:path=>({path,get:async()=>snap(path)}),runTransaction:work=>{const run=queue.then(async()=>{const writes=[];const tx={get:async ref=>{if(writes.length)throw Error('Read after write');return snap(ref.path);},set:(ref,value)=>writes.push([ref.path,value]),create:(ref,value)=>writes.push([ref.path,value]),delete:ref=>writes.push([ref.path,null])};const result=await work(tx);for(const [path,value]of writes)value===null?docs.delete(path):docs.set(path,value);return result;});queue=run.catch(()=>{});return run;}};
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
const backend=createHostDiscovery({db,FieldValue:{serverTimestamp:()=>123},HttpsError});
beforeEach(()=>{queue=Promise.resolve();docs.clear();docs.set('users/c',{role:'consumer'});docs.set('users/p',{role:'host',hostStatus:{isApproved:false}});docs.set('users/h',{hostStatus:{isApproved:true}});docs.set('users/h2',{hostStatus:{isApproved:true}});});
test('parallel Like is one relationship and unlike is idempotent',async()=>{const result=await Promise.all([backend.setLike('c',{hostId:'h',liked:true}),backend.setLike('c',{hostId:'h',liked:true})]);expect(result.map(value=>value.idempotent)).toEqual([false,true]);expect(docs.get('users/h/likes/c')).toEqual({consumerId:'c',hostId:'h',createdAt:123});await backend.setLike('c',{hostId:'h',liked:false});expect((await backend.setLike('c',{hostId:'h',liked:false})).idempotent).toBe(true);});
test('pending acts as Consumer, Hosts cannot use Consumer Like',async()=>{await backend.setLike('p',{hostId:'h',liked:true});await expect(backend.setLike('h2',{hostId:'h',liked:true})).rejects.toMatchObject({code:'permission-denied'});await expect(backend.setLike('c',{hostId:'p',liked:true})).rejects.toMatchObject({code:'permission-denied'});});
test('Like rejects spoofed ownership, self, unknown profiles, and either block',async()=>{await expect(backend.setLike('c',{hostId:'h',liked:true,consumerId:'p'})).rejects.toMatchObject({code:'invalid-argument'});await expect(backend.setLike('c',{hostId:'c',liked:true})).rejects.toMatchObject({code:'invalid-argument'});await expect(backend.setLike('c',{hostId:'missing',liked:true})).rejects.toMatchObject({code:'permission-denied'});for(const path of ['users/h/blocked/c','users/c/blocked/h']){docs.set(path,{});await expect(backend.setLike('c',{hostId:'h',liked:true})).rejects.toMatchObject({code:'permission-denied'});docs.delete(path);}});
test('atomic block removes both follow directions and Like; delayed event after unblock preserves new follow',async()=>{docs.set('users/h/likes/c',{});docs.set('users/c/following/h',{});docs.set('users/h/following/c',{});await backend.cleanup('c','h',true);expect(docs.has('users/h/likes/c')).toBe(false);expect(docs.has('users/c/following/h')).toBe(false);expect(docs.has('users/h/following/c')).toBe(false);docs.delete('users/c/blocked/h');docs.set('users/c/following/h',{});expect(await backend.cleanup('c','h')).toEqual({blocked:false});expect(docs.has('users/c/following/h')).toBe(true);});
test('Not Interested is a separate preference, not a block',async()=>{await backend.hide('p','h');expect(docs.has('users/p/discoveryHidden/h')).toBe(true);expect([...docs.keys()].some(path=>path.includes('/blocked/'))).toBe(false);});
test('public projection excludes private data and ignores untrusted date/rate/availability defaults',()=>{const host=projectHost('h',{hostApprovedAt:'2026-09-18',email:'secret',wallet:{creditBalance:500},payoutSetup:{bank:'secret'},hostStatus:{availability:'unknown'},hostProfile:{interests:['music','fake','Travel','Music']}},null);expect(host.hostApprovedAt).toBeNull();expect(host.hostProfile.videoRateCredits).toBeNull();expect(host.hostStatus.availability).toBe('offline');expect(host.hostProfile.interests).toEqual(['Music','Travel']);expect(host).not.toHaveProperty('email');expect(host).not.toHaveProperty('wallet');expect(host).not.toHaveProperty('payoutSetup');});
test('trusted approved application date and real rate survive public projection',()=>{const now=Date.parse('2026-09-18T12:00:00Z');expect(projectHost('h',{hostProfile:{videoRateCredits:37}}, {status:'approved',approvedAt:new Date(now-1000)},now)).toMatchObject({hostApprovedAt:now-1000,hostProfile:{videoRateCredits:37}});expect(projectHost('h',{}, {status:'submitted',approvedAt:new Date(now-1000)},now).hostApprovedAt).toBeNull();});
test('only valid DOB determines age; no legacy invented age',()=>{expect(ageFromDob('2000-09-19',Date.parse('2026-09-18'))).toBe(25);for(const value of ['2000-02-30','bad','2030-01-01','2010-01-01'])expect(ageFromDob(value,Date.parse('2026-09-18'))).toBeNull();expect(projectHost('h',{age:28},{},Date.now()).age).toBeNull();});
test('controlled interests and public media exclude invalid/VIP references',()=>{expect(controlledInterests(Array(20).fill('Music'))).toEqual(['Music']);expect(publicPhotos({profilePic:'https://media.example/a',hostProfile:{gallery:['https://media.example/a',{url:'https://media.example/private',visibility:'vip_only'},'file:///local','https://media.example/b']}})).toEqual(['https://media.example/a','https://media.example/b']);const host=projectHost('h',{stories:[{uri:'https://media.example/a',visibility:'public',expiresAt:'2026-09-19'},{uri:'https://media.example/private',visibility:'vip_only',expiresAt:'2026-09-19'},{uri:'https://media.example/expired',visibility:'public',expiresAt:'2026-09-17'}],moments:[{uri:'https://media.example/private',visibility:'VIP Only'},{uri:'https://media.example/a',visibility:'public'}]},null,Date.parse('2026-09-18'));expect(host.stories).toHaveLength(1);expect(host.moments).toHaveLength(1);});
