'use strict';
const Q=require('../quickMatchDomain');
const consumer={role:'consumer',uid:'c',countryCode:'GH',preferences:{interests:['music']}};
const host=(uid,extra={})=>({uid,role:'host',hostStatus:{isApproved:true,availability:'online'},hostProfile:{interests:[]},...extra});
test('consumer and pending applicant are eligible',()=>{expect(Q.eligibleConsumer(consumer)).toBe(true);expect(Q.eligibleConsumer({...consumer,creatorApplication:{status:'pending'}})).toBe(true)});
test('approved host and demo cannot start',()=>{expect(Q.eligibleConsumer({role:'host'})).toBe(false);expect(Q.eligibleConsumer({...consumer,isDemo:true})).toBe(false)});
test('reservation is distinct from consumption',()=>{expect(Q.reserve({quickMatchCount:2})).toEqual({quickMatchCount:2,quickMatchReserved:1})});
test('release restores availability without minting',()=>{expect(Q.release({quickMatchCount:2,quickMatchReserved:1})).toEqual({quickMatchCount:2,quickMatchReserved:0})});
test('commit consumes exactly one reserved entitlement',()=>{expect(Q.consume({quickMatchCount:2,quickMatchReserved:1})).toEqual({quickMatchCount:1,quickMatchReserved:0})});
test('missing reservation cannot consume',()=>expect(()=>Q.consume({quickMatchCount:2})).toThrow('reservation-missing'));
test('active and terminal states are explicit',()=>{expect(Q.isActive('offering')).toBe(true);expect(Q.TERMINAL.has('no_match')).toBe(true)});
test('terminal states cannot restart',()=>expect(Q.canTransition('no_match','searching')).toBe(false));
test('acceptance is allowed only from offering',()=>{expect(Q.canTransition('offering','accepted')).toBe(true);expect(Q.canTransition('searching','accepted')).toBe(false)});
test('candidate selection is online approved non-demo only',()=>expect(Q.rankCandidates([host('a'),host('b',{isDemo:true}),host('c',{hostStatus:{isApproved:true,availability:'offline'}})],consumer)).toEqual(['a']));
test('candidate selection is deterministic and capped at three',()=>expect(Q.rankCandidates([host('d'),host('c'),host('b'),host('a')],consumer)).toEqual(['a','b','c']));
test('country and interests are safe ranking signals',()=>expect(Q.rankCandidates([host('a'),host('b',{countryCode:'GH',hostProfile:{interests:['music']}})],consumer)[0]).toBe('b'));
test('VIP and Level do not affect ranking',()=>expect(Q.rankCandidates([host('a',{vip:{state:'VIP'},amiraLevel:10}),host('b')],consumer)).toEqual(['a','b']));
test('search projection never leaks candidates',()=>expect(Q.safeConsumerRequest({requestId:'r',status:'offering',fundingSource:'entitlement',candidateIds:['secret'],expiresAtMs:9},1)).not.toHaveProperty('candidateIds'));
test('accepted identity appears only after acceptance',()=>{const base={requestId:'r',fundingSource:'entitlement',acceptedHostIdentity:{uid:'h'},expiresAtMs:9};expect(Q.safeConsumerRequest({...base,status:'offering'},1).host).toBeNull();expect(Q.safeConsumerRequest({...base,status:'accepted'},1).host).toEqual({uid:'h'})});
test('paid fallback has no domain price',()=>expect(Q).not.toHaveProperty('PRICE'));
test('searching and ringing consume zero intro',()=>expect(Q.connectedAllocation(0,10)).toEqual({introSeconds:0,freeVideoSeconds:0,paidEligibleSeconds:0}));
test('intro consumes first twenty connected seconds',()=>expect(Q.connectedAllocation(19000,10)).toEqual({introSeconds:19,freeVideoSeconds:0,paidEligibleSeconds:0}));
test('Free Video Time follows intro',()=>expect(Q.connectedAllocation(25000,10)).toEqual({introSeconds:20,freeVideoSeconds:5,paidEligibleSeconds:0}));
test('paid eligibility follows intro and Free Video Time',()=>expect(Q.connectedAllocation(35000,10)).toEqual({introSeconds:20,freeVideoSeconds:10,paidEligibleSeconds:5}));
