'use strict';
const {initializeApp}=require('firebase-admin/app');
const {getFirestore,FieldValue,Timestamp}=require('firebase-admin/firestore');
const {onCall,HttpsError}=require('firebase-functions/v2/https');
const {onSchedule}=require('firebase-functions/v2/scheduler');
const {defineSecret,defineString}=require('firebase-functions/params');
const {RtcTokenBuilder,RtcRole}=require('agora-token');
const crypto=require('node:crypto');
const D=require('./callDomain');
initializeApp(); const db=getFirestore();
const AGORA_APP_CERTIFICATE=defineSecret('AGORA_APP_CERTIFICATE');
const AGORA_APP_ID=defineString('AGORA_APP_ID');
const region='us-central1';
const callable={region,enforceAppCheck:false};
const requireAuth=(request)=>{if(!request.auth?.uid)throw new HttpsError('unauthenticated','Sign in is required.');return request.auth.uid;};
const textId=(value,name)=>{if(typeof value!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(value))throw new HttpsError('invalid-argument',`Invalid ${name}.`);return value;};
const mapError=(error)=>{if(error instanceof HttpsError)return error;const code={
  'self-call':'invalid-argument','unapproved-creator':'failed-precondition','creator-unavailable':'failed-precondition',blocked:'permission-denied','active-call-conflict':'already-exists','not-receiver':'permission-denied','not-ringable':'failed-precondition','not-participant':'permission-denied','demo-profile':'failed-precondition',
}[error.message]||'failed-precondition';return new HttpsError(code,({blocked:'Calls are unavailable for this connection.','active-call-conflict':'A participant is already in another call.','creator-unavailable':'Creator unavailable.','unapproved-creator':'Creator is not approved for calls.','not-ringable':'This call can no longer be answered.','not-participant':'You are not a participant in this call.','self-call':'You cannot call yourself.','demo-profile':'Demo profiles cannot use production calling.'}[error.message]||'The call request could not be completed.'));};
const blockedRefs=(a,b)=>[db.doc(`users/${a}/blocked/${b}`),db.doc(`users/${b}/blocked/${a}`)];
const randomRtcUid=()=>crypto.randomInt(1,2147483647);
const callResult=(id,data)=>({callId:id,status:data.status,callerId:data.callerId,receiverId:data.receiverId,participantIds:data.participantIds,ratePerMinute:data.ratePerMinute,previewEligible:data.previewEligible,billingMode:data.billingMode,expiresAtMs:data.expiresAtMs});

exports.startVideoCall=onCall(callable,async(request)=>{try{const callerId=requireAuth(request),creatorId=textId(request.data?.creatorId,'creatorId');const callRef=db.collection('calls').doc(),callerRef=db.doc(`users/${callerId}`),creatorRef=db.doc(`users/${creatorId}`),callerLock=db.doc(`activeCallLocks/${callerId}`),creatorLock=db.doc(`activeCallLocks/${creatorId}`),entitlementRef=db.doc(`users/${callerId}/entitlements/dailyPreview`);return await db.runTransaction(async(tx)=>{const [callerSnap,creatorSnap,callerLockSnap,creatorLockSnap,entSnap,...blocks]=await Promise.all([tx.get(callerRef),tx.get(creatorRef),tx.get(callerLock),tx.get(creatorLock),tx.get(entitlementRef),...blockedRefs(callerId,creatorId).map((ref)=>tx.get(ref))]);const creator=creatorSnap.data();D.validateStart({authUid:callerId,creatorId,creator,blocked:blocks.some((s)=>s.exists),callerLock:callerLockSnap.exists,creatorLock:creatorLockSnap.exists});if(!callerSnap.exists)throw new Error('caller-missing');const rate=creator.hostProfile?.videoRateCredits;if(!Number.isInteger(rate)||rate<=0)throw new Error('invalid-rate');const now=Date.now(),dateKey=D.utcDateKey(),eligible=D.previewEligible(entSnap.data(),dateKey),channelName=`amira_${callRef.id}_${crypto.randomBytes(8).toString('hex')}`;let callerRtcUid=randomRtcUid(),creatorRtcUid=randomRtcUid();while(creatorRtcUid===callerRtcUid)creatorRtcUid=randomRtcUid();const data={id:callRef.id,callerId,receiverId:creatorId,participantIds:[callerId,creatorId],status:'ringing',createdAt:FieldValue.serverTimestamp(),createdAtMs:now,expiresAt:Timestamp.fromMillis(now+D.RING_TIMEOUT_SECONDS*1000),expiresAtMs:now+D.RING_TIMEOUT_SECONDS*1000,acceptedAt:null,connectedAt:null,endedAt:null,durationSeconds:0,paidDurationSeconds:0,ratePerMinute:rate,previewEligible:eligible,previewConsumed:false,billingMode:eligible?D.BILLING_MODES.PREVIEW:D.BILLING_MODES.AWAITING_PAID_CONFIRMATION,billedCredits:0,settledIncrements:0,paidStartedAt:null,paidStartedAtMs:null,endedBy:null,endReason:null,rtc:{channelName,uids:{[callerId]:callerRtcUid,[creatorId]:creatorRtcUid}},rtcAcks:{},lastRtcPresenceAt:null};tx.create(callRef,data);const lock={callId:callRef.id,createdAt:FieldValue.serverTimestamp(),expiresAtMs:data.expiresAtMs};tx.create(callerLock,lock);tx.create(creatorLock,lock);return callResult(callRef.id,data);});}catch(e){throw mapError(e);}});

exports.respondToVideoCall=onCall(callable,async(request)=>{try{const uid=requireAuth(request),callId=textId(request.data?.callId,'callId'),action=request.data?.action;if(!['accept','decline'].includes(action))throw new HttpsError('invalid-argument','Action must be accept or decline.');const callRef=db.doc(`calls/${callId}`);return await db.runTransaction(async(tx)=>{const callSnap=await tx.get(callRef);if(!callSnap.exists)throw new HttpsError('not-found','Call not found.');const call=callSnap.data(),creatorRef=db.doc(`users/${call.receiverId}`),creatorSnap=await tx.get(creatorRef);D.validateAcceptance({authUid:uid,call,creator:creatorSnap.data()});if(action==='decline'){tx.update(callRef,{status:'rejected',endedAt:FieldValue.serverTimestamp(),endedBy:uid,endReason:'declined',billingMode:D.BILLING_MODES.ENDED});tx.set(db.doc(`callHistory/${callId}`),{callId,participantIds:call.participantIds,callerId:call.callerId,receiverId:call.receiverId,createdAt:call.createdAt,endedAt:FieldValue.serverTimestamp(),durationSeconds:0,paidDurationSeconds:0,ratePerMinute:call.ratePerMinute,billedCredits:0,billingMode:call.billingMode,previewConsumed:false,endReason:'declined',status:'rejected'});tx.delete(db.doc(`activeCallLocks/${call.callerId}`));tx.delete(db.doc(`activeCallLocks/${call.receiverId}`));return {callId,status:'rejected'};}tx.update(callRef,{status:'connecting',acceptedAt:FieldValue.serverTimestamp()});tx.update(creatorRef,{'hostStatus.availability':'busy','hostStatus.preCallAvailability':creatorSnap.data().hostStatus?.availability||'online'});return {callId,status:'connecting'};});}catch(e){throw mapError(e);}});

exports.getVideoCallRtcCredentials=onCall({...callable,secrets:[AGORA_APP_CERTIFICATE]},async(request)=>{try{const uid=requireAuth(request),callId=textId(request.data?.callId,'callId'),appId=AGORA_APP_ID.value(),certificate=AGORA_APP_CERTIFICATE.value();if(!appId||!certificate)throw new HttpsError('failed-precondition','Video calling is temporarily unavailable.');const snap=await db.doc(`calls/${callId}`).get();if(!snap.exists)throw new HttpsError('not-found','Call not found.');const call=snap.data();D.assertParticipant(uid,call);if(!['connecting','connected'].includes(call.status))throw new HttpsError('failed-precondition','RTC access is not authorized for this call.');const rtcUid=D.sanitizeRtcUid(call.rtc?.uids?.[uid]),expiresAt=Math.floor(Date.now()/1000)+D.RTC_TOKEN_SECONDS,token=RtcTokenBuilder.buildTokenWithUid(appId,certificate,call.rtc.channelName,rtcUid,RtcRole.PUBLISHER,D.RTC_TOKEN_SECONDS,D.RTC_TOKEN_SECONDS);return {appId,channelName:call.rtc.channelName,token,rtcUid,expiresAt:expiresAt*1000};}catch(e){throw mapError(e);}});

exports.acknowledgeVideoConnected=onCall(callable,async(request)=>{try{const uid=requireAuth(request),callId=textId(request.data?.callId,'callId');return await db.runTransaction(async(tx)=>{const ref=db.doc(`calls/${callId}`),snap=await tx.get(ref);if(!snap.exists)throw new HttpsError('not-found','Call not found.');const call=snap.data();D.assertParticipant(uid,call);if(!['connecting','connected'].includes(call.status))throw new Error('invalid-state');if(call.status==='connected')return callResult(callId,call);const acks={...(call.rtcAcks||{}),[uid]:{remotePresent:true,atMs:Date.now()}},patch={rtcAcks:acks,lastRtcPresenceAt:FieldValue.serverTimestamp()};if(D.shouldConnect(acks,call.participantIds)){const entitlementRef=db.doc(`users/${call.callerId}/entitlements/dailyPreview`),entSnap=await tx.get(entitlementRef),dateKey=D.utcDateKey(),eligible=D.previewEligible(entSnap.data(),dateKey);patch.status='connected';patch.connectedAt=FieldValue.serverTimestamp();patch.connectedAtMs=Date.now();patch.previewEligible=eligible;patch.previewConsumed=eligible;patch.billingMode=eligible?D.BILLING_MODES.PREVIEW:D.BILLING_MODES.AWAITING_PAID_CONFIRMATION;if(eligible)tx.set(entitlementRef,{dateKey,consumed:true,consumedAt:FieldValue.serverTimestamp(),callId},{merge:false});}tx.update(ref,patch);return {callId,status:patch.status||'connecting',billingMode:patch.billingMode||call.billingMode,previewEligible:patch.previewEligible??call.previewEligible};});}catch(e){throw mapError(e);}});

exports.confirmPaidContinuation=onCall(callable,async(request)=>{try{const uid=requireAuth(request),callId=textId(request.data?.callId,'callId');return await db.runTransaction(async(tx)=>{const callRef=db.doc(`calls/${callId}`),callSnap=await tx.get(callRef);if(!callSnap.exists)throw new HttpsError('not-found','Call not found.');const call=callSnap.data();D.assertParticipant(uid,call);if(uid!==call.callerId)throw new HttpsError('permission-denied','Only the consumer can confirm paid time.');if(call.status!=='connected'||call.billingMode!==D.BILLING_MODES.AWAITING_PAID_CONFIRMATION)throw new HttpsError('failed-precondition','Paid continuation is not available.');const userRef=db.doc(`users/${uid}`),userSnap=await tx.get(userRef),charge=D.incrementCredits(call.ratePerMinute);if((userSnap.data()?.wallet?.creditBalance||0)<charge)throw new HttpsError('resource-exhausted','Not enough credits to continue.');tx.update(callRef,{billingMode:D.BILLING_MODES.PAID,paidStartedAt:FieldValue.serverTimestamp(),paidStartedAtMs:Date.now(),lastRtcPresenceAt:FieldValue.serverTimestamp()});return {callId,billingMode:D.BILLING_MODES.PAID,incrementSeconds:D.BILLING_INCREMENT_SECONDS,incrementCredits:charge};});}catch(e){throw mapError(e);}});

exports.settleVideoCallIncrement=onCall(callable,async(request)=>{try{const uid=requireAuth(request),callId=textId(request.data?.callId,'callId');return await db.runTransaction(async(tx)=>{const callRef=db.doc(`calls/${callId}`),callSnap=await tx.get(callRef);if(!callSnap.exists)throw new HttpsError('not-found','Call not found.');const call=callSnap.data();D.assertParticipant(uid,call);if(call.status!=='connected'||call.billingMode!==D.BILLING_MODES.PAID)throw new HttpsError('failed-precondition','Paid billing is not active.');const next=(call.settledIncrements||0)+1,available=D.payableIncrementCount({paidStartedAtMs:call.paidStartedAtMs});if(next>available)return {settled:false,nextEligibleAtMs:call.paidStartedAtMs+next*D.BILLING_INCREMENT_SECONDS*1000};const ledgerRef=db.doc(`creditTransactions/${D.settlementId(callId,next)}`),ledgerSnap=await tx.get(ledgerRef);if(ledgerSnap.exists)return {settled:true,idempotent:true,...ledgerSnap.data()};const consumerRef=db.doc(`users/${call.callerId}`),creatorRef=db.doc(`users/${call.receiverId}`),consumerSnap=await tx.get(consumerRef),creatorSnap=await tx.get(creatorRef),credits=D.incrementCredits(call.ratePerMinute),balance=consumerSnap.data()?.wallet?.creditBalance||0;if(balance<credits){tx.update(callRef,{billingMode:D.BILLING_MODES.AWAITING_PAID_CONFIRMATION,endReason:'insufficient_credits'});return {settled:false,insufficientCredits:true};}const ledger={transactionId:ledgerRef.id,consumerId:call.callerId,creatorId:call.receiverId,callId,type:'video_call_increment',credits,grossCredits:credits,platformFeeCredits:null,creatorNetCredits:null,commissionPolicy:'pending',billingIncrement:next,idempotencyKey:ledgerRef.id,createdAt:FieldValue.serverTimestamp()};tx.update(consumerRef,{'wallet.creditBalance':balance-credits});tx.update(creatorRef,{'earnings.pending':(creatorSnap.data()?.earnings?.pending||0)+credits});tx.create(ledgerRef,ledger);tx.update(callRef,{settledIncrements:next,billedCredits:(call.billedCredits||0)+credits,lastRtcPresenceAt:FieldValue.serverTimestamp()});return {settled:true,transactionId:ledgerRef.id,incrementNumber:next,credits,balance:balance-credits};});}catch(e){throw mapError(e);}});

exports.endVideoCall=onCall(callable,async(request)=>{try{const uid=requireAuth(request),callId=textId(request.data?.callId,'callId'),reason=String(request.data?.reason||'participant_ended').slice(0,64);return await db.runTransaction(async(tx)=>{const callRef=db.doc(`calls/${callId}`),snap=await tx.get(callRef);if(!snap.exists)throw new HttpsError('not-found','Call not found.');const call=snap.data();D.assertParticipant(uid,call);if(D.TERMINAL_STATUSES.has(call.status))return {callId,status:call.status,idempotent:true};const creatorRef=db.doc(`users/${call.receiverId}`),creatorSnap=await tx.get(creatorRef),now=Date.now(),duration=call.connectedAtMs?Math.max(0,Math.floor((now-call.connectedAtMs)/1000)):0,paidDuration=call.paidStartedAtMs?Math.max(0,Math.floor((now-call.paidStartedAtMs)/1000)):0;tx.update(callRef,{status:'ended',billingMode:D.BILLING_MODES.ENDED,endedAt:FieldValue.serverTimestamp(),endedAtMs:now,endedBy:uid,endReason:reason,durationSeconds:duration,paidDurationSeconds:paidDuration});tx.set(db.doc(`callHistory/${callId}`),{callId,participantIds:call.participantIds,callerId:call.callerId,receiverId:call.receiverId,createdAt:call.createdAt,acceptedAt:call.acceptedAt,connectedAt:call.connectedAt,endedAt:FieldValue.serverTimestamp(),durationSeconds:duration,paidDurationSeconds:paidDuration,ratePerMinute:call.ratePerMinute,billedCredits:call.billedCredits||0,billingMode:call.billingMode,previewConsumed:call.previewConsumed===true,endReason:reason,status:'ended'},{merge:false});tx.delete(db.doc(`activeCallLocks/${call.callerId}`));tx.delete(db.doc(`activeCallLocks/${call.receiverId}`));if(creatorSnap.exists&&creatorSnap.data().hostStatus?.availability==='busy')tx.update(creatorRef,{'hostStatus.availability':creatorSnap.data().hostStatus?.preCallAvailability==='offline'?'offline':'online','hostStatus.preCallAvailability':FieldValue.delete()});return {callId,status:'ended',durationSeconds:duration,paidDurationSeconds:paidDuration,billedCredits:call.billedCredits||0};});}catch(e){throw mapError(e);}});

exports.reconcileExpiredVideoCalls=onSchedule({region,schedule:'every 5 minutes'},async()=>{const now=Date.now(),snapshot=await db.collection('calls').where('status','in',['requesting','ringing']).where('expiresAtMs','<=',now).limit(200).get();const batch=db.batch();snapshot.docs.forEach((docSnap)=>{const call=docSnap.data();batch.update(docSnap.ref,{status:'missed',billingMode:D.BILLING_MODES.ENDED,endedAt:FieldValue.serverTimestamp(),endedBy:'system',endReason:'ring_timeout'});batch.delete(db.doc(`activeCallLocks/${call.callerId}`));batch.delete(db.doc(`activeCallLocks/${call.receiverId}`));batch.set(db.doc(`callHistory/${docSnap.id}`),{callId:docSnap.id,participantIds:call.participantIds,callerId:call.callerId,receiverId:call.receiverId,createdAt:call.createdAt,endedAt:FieldValue.serverTimestamp(),durationSeconds:0,paidDurationSeconds:0,ratePerMinute:call.ratePerMinute,billedCredits:0,billingMode:call.billingMode,previewConsumed:false,endReason:'ring_timeout',status:'missed'});});await batch.commit();});

exports._test={mapError};
