'use strict';
const Q=require('./quickMatchDomain');
const E=require('./economyDomain');
const {isApprovedHost}=require('./accountRole');

const createQuickMatchService=({db,FieldValue,Timestamp,HttpsError,clock=()=>Date.now(),createId=()=>db.collection('_').doc().id,createRtc})=>{
  const fail=(code,message,details)=>{throw new HttpsError(code,message,details)};
  const requestRef=(uid,id)=>db.doc(`quickMatchRequests/${uid}/requests/${id}`);
  const activeRef=(uid)=>db.doc(`quickMatchActive/${uid}`);
  const rewardRef=(uid)=>db.doc(`consumerRewards/${uid}`);
  const publicHost=(profile,uid)=>({uid,username:profile?.username||'Host',profilePic:profile?.profilePic||null,countryName:profile?.countryName||null});
  const candidatePool=async()=>{const snap=await db.collection('users').where('role','==','host').where('hostStatus.isApproved','==',true).where('hostStatus.availability','==','online').limit(40).get();return snap.docs.map(doc=>({uid:doc.id,...doc.data()}));};
  const start=async(uid,input={})=>{
    if(!input||typeof input.requestId!=='string'||!/^[A-Za-z0-9_-]{8,128}$/.test(input.requestId)||Object.keys(input).some(k=>k!=='requestId'))fail('invalid-argument','A stable requestId is required.');
    const hosts=await candidatePool(), now=clock(), ref=requestRef(uid,input.requestId);
    return db.runTransaction(async tx=>{
      const userRef=db.doc(`users/${uid}`), [user,reward,active,existing,callLock]=await Promise.all([tx.get(userRef),tx.get(rewardRef(uid)),tx.get(activeRef(uid)),tx.get(ref),tx.get(db.doc(`activeCallLocks/${uid}`))]);
      if(existing.exists)return Q.safeConsumerRequest(existing.data(),now);
      if(!Q.eligibleConsumer(user.data()))fail('permission-denied','Quick Match is available to Consumer accounts only.');
      if(callLock.exists)fail('already-exists','You are already in a call.');
      if(active.exists&&Q.isActive(active.data()?.status)&&Number(active.data()?.expiresAtMs||0)>now)return Q.safeConsumerRequest(active.data(),now);
      const staleReservation=active.exists&&active.data()?.fundingStatus==='reserved'&&Number(active.data()?.expiresAtMs||0)<=now;
      if(!Q.mayReserve(reward.data())&&!staleReservation)fail('resource-exhausted','A Quick Match entitlement is required.',{reason:'quick_match_entitlement_required',paidFallbackAvailable:false});
      const ranked=Q.rankCandidates(hosts,user.data());
      const checks=[];for(const hostId of ranked)checks.push(tx.get(db.doc(`activeCallLocks/${hostId}`)),tx.get(db.doc(`users/${uid}/blocked/${hostId}`)),tx.get(db.doc(`users/${hostId}/blocked/${uid}`)));
      const snapshots=await Promise.all(checks), candidates=ranked.filter((id,index)=>!snapshots[index*3].exists&&!snapshots[index*3+1].exists&&!snapshots[index*3+2].exists);
      const base={requestId:input.requestId,consumerUid:uid,fundingSource:'entitlement',fundingStatus:candidates.length?'reserved':'none',candidateIds:candidates,attemptIndex:candidates.length?0:-1,createdAt:FieldValue.serverTimestamp(),createdAtMs:now,expiresAtMs:now+Q.REQUEST_SECONDS*1000,callId:null,acceptedHostId:null};
      let rewardState=reward.data();
      if(staleReservation){rewardState={...rewardState,...Q.release(rewardState)};const staleRef=requestRef(uid,active.data().requestId),stale=await tx.get(staleRef);if(stale.exists)tx.update(staleRef,{status:'expired',fundingStatus:'released',endedAt:FieldValue.serverTimestamp(),endReason:'request_expired'});}
      if(!candidates.length){const data={...base,status:'no_match',endedAt:FieldValue.serverTimestamp(),endReason:'no_eligible_host'};if(staleReservation){tx.update(rewardRef(uid),{...rewardState,updatedAt:FieldValue.serverTimestamp()});tx.delete(activeRef(uid));}tx.create(ref,data);return Q.safeConsumerRequest(data,now)}
      const data={...base,status:'offering',offeredHostId:candidates[0],offerDeadlineMs:now+Q.OFFER_SECONDS*1000};
      const balance=Q.reserve(rewardState);tx.update(rewardRef(uid),{...balance,updatedAt:FieldValue.serverTimestamp()});tx.create(ref,data);tx.set(activeRef(uid),data);return Q.safeConsumerRequest(data,now);
    });
  };
  const state=async(uid,input={})=>{if(input&&Object.keys(input).length)fail('invalid-argument','Invalid Quick Match state request.');const now=clock(),initial=await activeRef(uid).get();if(!initial.exists)return {status:'idle',serverNowMs:now};if(initial.data().status!=='offering'||now<initial.data().offerDeadlineMs)return Q.safeConsumerRequest(initial.data(),now);return db.runTransaction(async tx=>{const active=await tx.get(activeRef(uid));if(!active.exists)return {status:'idle',serverNowMs:now};const current=active.data();if(current.status!=='offering'||now<current.offerDeadlineMs)return Q.safeConsumerRequest(current,now);const ref=requestRef(uid,current.requestId),snap=await tx.get(ref),request=snap.data();let chosen=null,index=request.attemptIndex;while(++index<request.candidateIds.length&&!chosen){const id=request.candidateIds[index],[profile,lock,...blocks]=await Promise.all([tx.get(db.doc(`users/${id}`)),tx.get(db.doc(`activeCallLocks/${id}`)),tx.get(db.doc(`users/${uid}/blocked/${id}`)),tx.get(db.doc(`users/${id}/blocked/${uid}`))]);if(Q.eligibleHost(profile.data(),lock.exists)&&!blocks.some(x=>x.exists))chosen=id}if(chosen){const patch={status:'offering',offeredHostId:chosen,attemptIndex:index,offerDeadlineMs:now+Q.OFFER_SECONDS*1000};tx.update(ref,patch);tx.update(activeRef(uid),patch);return Q.safeConsumerRequest({...request,...patch},now)}const reward=await tx.get(rewardRef(uid)),released=Q.release(reward.data()),patch={status:'no_match',fundingStatus:'released',endedAt:FieldValue.serverTimestamp(),endReason:'candidates_exhausted'};tx.update(rewardRef(uid),{...released,updatedAt:FieldValue.serverTimestamp()});tx.update(ref,patch);tx.delete(activeRef(uid));return Q.safeConsumerRequest({...request,...patch},now)});};
  const offer=async(uid,input={})=>{if(input&&Object.keys(input).length)fail('invalid-argument','Invalid offer request.');const now=clock(),snap=await db.collectionGroup('requests').where('offeredHostId','==',uid).where('status','==','offering').limit(1).get();if(snap.empty)return {offer:null,serverNowMs:now};const doc=snap.docs[0],value=doc.data();if(now>=value.offerDeadlineMs)return {offer:null,serverNowMs:now};const consumer=await db.doc(`users/${value.consumerUid}`).get();return {offer:{requestId:value.requestId,consumerUid:value.consumerUid,identity:{uid:value.consumerUid,username:consumer.data()?.username||'Consumer',profilePic:consumer.data()?.profilePic||null,countryName:consumer.data()?.countryName||null},context:'quick_match',deadlineMs:value.offerDeadlineMs},serverNowMs:now}};
  const respond=async(uid,input={})=>{if(!input||typeof input.consumerUid!=='string'||typeof input.requestId!=='string'||!['accept','decline'].includes(input.action)||Object.keys(input).some(k=>!['consumerUid','requestId','action'].includes(k)))fail('invalid-argument','Invalid Quick Match response.');const now=clock(),ref=requestRef(input.consumerUid,input.requestId);return db.runTransaction(async tx=>{
    const snap=await tx.get(ref);if(!snap.exists)fail('not-found','Quick Match request not found.');const request=snap.data();if(['accepted','connecting','connected'].includes(request.status)&&request.acceptedHostId===uid&&input.action==='accept')return {requestId:request.requestId,status:request.status,callId:request.callId,idempotent:true};
    if(request.status!=='offering'||request.offeredHostId!==uid)fail('permission-denied','This offer is not available to this Host.');
    const hostRef=db.doc(`users/${uid}`),consumerRef=db.doc(`users/${request.consumerUid}`),hostLockRef=db.doc(`activeCallLocks/${uid}`),consumerLockRef=db.doc(`activeCallLocks/${request.consumerUid}`);
    const [host,consumer,hostLock,consumerLock,...blocks]=await Promise.all([tx.get(hostRef),tx.get(consumerRef),tx.get(hostLockRef),tx.get(consumerLockRef),tx.get(db.doc(`users/${uid}/blocked/${request.consumerUid}`)),tx.get(db.doc(`users/${request.consumerUid}/blocked/${uid}`))]);
    const timedOut=now>=request.offerDeadlineMs, invalid=!Q.eligibleHost(host.data(),hostLock.exists)||!Q.eligibleConsumer(consumer.data())||consumerLock.exists||blocks.some(x=>x.exists);
    if(input.action==='decline'||timedOut||invalid){let nextIndex=request.attemptIndex,nextId=null;while(++nextIndex<request.candidateIds.length&&!nextId&&now<request.expiresAtMs){const candidate=request.candidateIds[nextIndex],[nextHost,nextLock,...nextBlocks]=await Promise.all([tx.get(db.doc(`users/${candidate}`)),tx.get(db.doc(`activeCallLocks/${candidate}`)),tx.get(db.doc(`users/${candidate}/blocked/${request.consumerUid}`)),tx.get(db.doc(`users/${request.consumerUid}/blocked/${candidate}`))]);if(Q.eligibleHost(nextHost.data(),nextLock.exists)&&!nextBlocks.some(item=>item.exists))nextId=candidate}if(nextId){const patch={status:'offering',offeredHostId:nextId,attemptIndex:nextIndex,offerDeadlineMs:now+Q.OFFER_SECONDS*1000};tx.update(ref,patch);tx.update(activeRef(request.consumerUid),patch);return {requestId:request.requestId,status:'offering'}}
      const reward=await tx.get(rewardRef(request.consumerUid)),balance=Q.release(reward.data()),patch={status:'no_match',fundingStatus:'released',endedAt:FieldValue.serverTimestamp(),endReason:timedOut?'offer_timeout':invalid?'candidate_invalid':'declined'};tx.update(rewardRef(request.consumerUid),{...balance,updatedAt:FieldValue.serverTimestamp()});tx.update(ref,patch);tx.delete(activeRef(request.consumerUid));return {requestId:request.requestId,status:'no_match'};}
    const rate=host.data()?.hostProfile?.videoRateCredits;if(!Number.isInteger(rate)||rate<=0)fail('failed-precondition','Host call pricing is unavailable.');
    const callId=createId(),callRef=db.doc(`calls/${callId}`),rtc=createRtc(callId,request.consumerUid,uid),deadline=now+require('./connectionAccounting').CONNECTING_TIMEOUT_MS;
    const call={accountingVersion:2,id:callId,source:'quick_match',quickMatchRequestId:request.requestId,callerId:request.consumerUid,receiverId:uid,participantIds:[request.consumerUid,uid],status:'connecting',createdAt:FieldValue.serverTimestamp(),createdAtMs:now,acceptedAt:FieldValue.serverTimestamp(),connectingDeadlineMs:deadline,expiresAtMs:deadline,connectedAt:null,endedAt:null,durationSeconds:0,paidDurationSeconds:0,ratePerMinute:rate,previewEligible:false,previewConsumed:false,billingMode:'preview',billedCredits:0,settledIncrements:0,paidStartedAt:null,paidStartedAtMs:null,endedBy:null,endReason:null,quickMatchIntroSeconds:Q.INTRO_SECONDS,rtc,rtcAcks:{},lastRtcPresenceAt:null};
    const lock={callId,source:'quick_match',quickMatchRequestId:request.requestId,createdAt:FieldValue.serverTimestamp(),expiresAtMs:deadline};tx.create(callRef,call);tx.create(hostLockRef,lock);tx.create(consumerLockRef,lock);tx.update(hostRef,{'hostStatus.availability':'busy','hostStatus.preCallAvailability':'online'});const patch={status:'connecting',acceptedHostId:uid,acceptedHostIdentity:publicHost(host.data(),uid),callId,acceptedAt:FieldValue.serverTimestamp(),offeredHostId:null};tx.update(ref,patch);tx.update(activeRef(request.consumerUid),patch);return {requestId:request.requestId,status:'connecting',callId,host:patch.acceptedHostIdentity};
  })};
  const finish=async(uid,input={},reason='cancelled')=>{if(!input||typeof input.requestId!=='string'||Object.keys(input).some(k=>k!=='requestId'))fail('invalid-argument','Invalid cancellation.');const now=clock(),ref=requestRef(uid,input.requestId);return db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)fail('not-found','Quick Match request not found.');const request=snap.data();if(Q.TERMINAL.has(request.status))return {requestId:request.requestId,status:request.status,idempotent:true};if(request.status==='connected')fail('failed-precondition','End the connected call normally.');const reward=await tx.get(rewardRef(uid)),hostRef=request.acceptedHostId?db.doc(`users/${request.acceptedHostId}`):null,host=hostRef?await tx.get(hostRef):null,locks=[db.doc(`activeCallLocks/${uid}`),...(request.acceptedHostId?[db.doc(`activeCallLocks/${request.acceptedHostId}`)]:[])],lockSnaps=await Promise.all(locks.map(x=>tx.get(x)));if(request.fundingStatus==='reserved'){const balance=Q.release(reward.data());tx.update(rewardRef(uid),{...balance,updatedAt:FieldValue.serverTimestamp()})}const patch={status:reason,fundingStatus:'released',endedAt:FieldValue.serverTimestamp(),endReason:reason};tx.update(ref,patch);tx.delete(activeRef(uid));if(request.callId)tx.update(db.doc(`calls/${request.callId}`),{status:'cancelled',billingMode:'ended',endedAt:FieldValue.serverTimestamp(),endedAtMs:now,endReason:reason});lockSnaps.forEach((s,i)=>{if(s.data()?.quickMatchRequestId===request.requestId)tx.delete(locks[i])});if(host?.data()?.hostStatus?.availability==='busy')tx.update(hostRef,{'hostStatus.availability':host.data().hostStatus?.preCallAvailability||'online','hostStatus.preCallAvailability':FieldValue.delete()});return {requestId:request.requestId,status:reason}})};
  return {start,state,offer,respond,cancel:(uid,input)=>finish(uid,input,'cancelled'),reconcile:(uid,input)=>finish(uid,input,'expired')};
};
module.exports={createQuickMatchService};
