const mockGetDocs=jest.fn(),mockQuery=jest.fn((...parts)=>parts),mockStartAfter=jest.fn(cursor=>['after',cursor]);
jest.mock('firebase/firestore',()=>({collection:jest.fn((_db,name)=>['collection',name]),getDocs:(...args)=>mockGetDocs(...args),limit:jest.fn(value=>['limit',value]),orderBy:jest.fn((field,direction)=>['order',field,direction]),query:(...args)=>mockQuery(...args),startAfter:(...args)=>mockStartAfter(...args),where:jest.fn((...args)=>['where',...args])}));
jest.mock('../firebaseService',()=>({auth:{currentUser:{uid:'owner'}},db:{}}));
const {CALL_HISTORY_PAGE_SIZE,buildCallHistoryRecord,callHistoryService}=require('../callHistoryService');

const doc=(id,data={})=>({id,data:()=>data});
beforeEach(()=>{jest.clearAllMocks();});

test('first page is participant-filtered, newest-first, bounded, and returns an opaque final-document cursor',async()=>{const last=doc('b',{participantIds:['owner','host']});mockGetDocs.mockResolvedValue({docs:[doc('a'),last]});const page=await callHistoryService.listPage({pageSize:2});expect(page).toEqual({records:[{id:'a'},{id:'b',participantIds:['owner','host']}],cursor:last,hasMore:true});expect(mockQuery.mock.calls[0]).toEqual([["collection","callHistory"],["where","participantIds","array-contains","owner"],["order","createdAt","desc"],["limit",2]]);expect(mockStartAfter).not.toHaveBeenCalled();});
test('next page advances with startAfter and reports a clear end state',async()=>{const cursor=doc('cursor');mockGetDocs.mockResolvedValue({docs:[doc('older')]});const page=await callHistoryService.listPage({cursor,pageSize:2});expect(mockStartAfter).toHaveBeenCalledWith(cursor);expect(mockQuery.mock.calls[0][3]).toEqual(['after',cursor]);expect(page).toMatchObject({records:[{id:'older'}],cursor:expect.anything(),hasMore:false});});
test('page size is capped and signed-out access returns no query or records',async()=>{const {auth}=require('../firebaseService');auth.currentUser=null;expect(await callHistoryService.listPage({pageSize:999})).toEqual({records:[],cursor:null,hasMore:false});expect(mockGetDocs).not.toHaveBeenCalled();auth.currentUser={uid:'owner'};mockGetDocs.mockResolvedValue({docs:[]});await callHistoryService.listPage({pageSize:999});expect(mockQuery.mock.calls[0].at(-1)).toEqual(['limit',50]);});
test('client presentation record excludes billing fields and never fabricates missing duration',()=>{expect(buildCallHistoryRecord({id:'call',billedCredits:99,participantIds:['owner','host']})).toEqual(expect.objectContaining({callId:'call',durationSeconds:undefined,source:'direct'}));expect(buildCallHistoryRecord({id:'call',billedCredits:99})).not.toHaveProperty('billedCredits');});
