import React from 'react';
import {act,render} from '@testing-library/react-native';
jest.setTimeout(30000);
let mockUser,mockTarget;
const mockLevel={getConsumer:jest.fn()};
jest.mock('../../../context/UserContext',()=>({useUser:()=>({user:mockUser})}));
jest.mock('@react-navigation/native',()=>({useIsFocused:()=>true}));
jest.mock('../../../services/levelService',()=>({levelService:mockLevel}));
jest.mock('../../../services/firebaseService',()=>({dbService:{getUserProfile:async()=>mockTarget}}));
jest.mock('../../../services/callReviewService',()=>({callReviewService:{subscribeReputation:()=>()=>{}}}));
jest.mock('../../../services/followService',()=>({canFollowProfile:()=>false,followService:{isFollowing:async()=>false,subscribeRelationship:()=>()=>{},subscribeFollowerCount:(_id,callback)=>{callback(0);return()=>{};}}}));
jest.mock('../../../services/blockService',()=>({blockService:{getRelationship:async()=>({blocked:false})}}));
jest.mock('../../../services/reportService',()=>({reportService:{}}));
jest.mock('../../../services/profileViewService',()=>({profileViewService:{track:async()=>{}}}));
jest.mock('../../../services/callNavigationService',()=>({startVideoCall:jest.fn()}));
jest.mock('../../../services/callService',()=>({callService:{}}));
jest.mock('../../../services/discoveryService',()=>({discoveryService:{getConsumersForHosts:async()=>[mockTarget]}}));
jest.mock('../../../components/IncomingCallCard',()=>()=>null);
jest.mock('../../../components/ReportUserModal',()=>()=>null);
jest.mock('expo-video',()=>({VideoView:()=>null,useVideoPlayer:()=>({})}));
jest.mock('lucide-react-native',()=>Object.fromEntries(['BadgeCheck','ChevronLeft','Flag','MessageCircle','ShieldAlert','UserMinus','UserPlus','Video'].map(key=>[key,()=>null])));
const Profile=require('../UserProfileScreen').default,Connect=require('../../host/HostDashboardScreen').default;
const flush=async()=>act(async()=>{for(let i=0;i<12;i++)await Promise.resolve();});
beforeEach(()=>{jest.clearAllMocks();mockUser={uid:'h',role:'host',hostStatus:{isApproved:true,availability:'offline'}};mockTarget={uid:'c',username:'Real Consumer',role:'consumer',age:25,countryCode:'GH',level:10,amiraLevel:10,wallet:{creditBalance:99999}};mockLevel.getConsumer.mockResolvedValue({level:0});});
test('approved Host full profile uses backend derived badge, ignores cached level/wallet',async()=>{const screen=render(<Profile route={{params:{userId:'c'}}} navigation={{}}/>);await flush();expect(mockLevel.getConsumer).toHaveBeenCalledWith('c');expect(screen.getByLabelText('Amira Level 0')).toBeTruthy();expect(screen.queryByLabelText('Amira Level 10')).toBeNull();screen.unmount();});
test('failed public lookup never displays a fabricated Consumer Level',async()=>{mockLevel.getConsumer.mockRejectedValue(new Error('blocked'));const screen=render(<Profile route={{params:{userId:'c'}}} navigation={{}}/>);await flush();expect(screen.queryByLabelText(/Amira Level/)).toBeNull();screen.unmount();});
test('small Host Connect Consumer cards have no Level badge or Level request',async()=>{const screen=render(<Connect navigation={{}}/>);await flush();expect(screen.getByText('Real Consumer')).toBeTruthy();expect(screen.queryByLabelText(/Amira Level/)).toBeNull();expect(mockLevel.getConsumer).not.toHaveBeenCalled();screen.unmount();});
