import React from 'react';
import {act,render} from '@testing-library/react-native';
jest.setTimeout(30000);
let mockUser,mockTarget;
const mockTrack=jest.fn(),mockHostGet=jest.fn(),mockConsumerGet=jest.fn();
jest.mock('../../../context/UserContext',()=>({useUser:()=>({user:mockUser})}));
jest.mock('@react-navigation/native',()=>({useIsFocused:()=>true}));
jest.mock('react-native-safe-area-context',()=>({useSafeAreaInsets:()=>({bottom:0})}));
jest.mock('../../../services/hostProfileService',()=>({hostProfileService:{get:mockHostGet}}));
jest.mock('../../../services/hostActivityService',()=>({hostActivityService:{getConsumer:mockConsumerGet}}));
jest.mock('../../../services/profileViewService',()=>({profileViewService:{track:mockTrack}}));
jest.mock('../../../services/levelService',()=>({levelService:{getConsumer:async()=>({level:0})}}));
jest.mock('../../../services/callReviewService',()=>({callReviewService:{subscribeReputation:()=>()=>{}}}));
jest.mock('../../../services/followService',()=>({canFollowProfile:()=>false,followService:{isFollowing:async()=>false,subscribeRelationship:(_id,callback)=>{callback({following:false,label:'Follow',blocked:false});return()=>{};}}}));
jest.mock('../../../services/blockService',()=>({blockService:{}}));
jest.mock('../../../services/reportService',()=>({reportService:{}}));
jest.mock('../../../services/callNavigationService',()=>({startVideoCall:jest.fn()}));
jest.mock('../../../components/ReportUserModal',()=>()=>null);
jest.mock('../../../components/GiftTray',()=>()=>null);
jest.mock('../../../services/giftService',()=>({giftService:{publicHostGifts:async()=>({gifts:[]})}}));
jest.mock('expo-video',()=>({VideoView:()=>null,useVideoPlayer:()=>({})}));
const Profile=require('../UserProfileScreen').default,Card=require('../../../components/HostCard').default;
const flush=async()=>act(async()=>{for(let i=0;i<12;i++)await Promise.resolve();});
beforeEach(()=>{jest.clearAllMocks();mockUser={uid:'c',hostStatus:{isApproved:false}};mockTarget={uid:'h',amiraId:'AMR-123456',username:'Real Host',hostStatus:{isApproved:true,availability:'offline'},hostProfile:{gallery:[],interests:[],videoRateCredits:37},social:{liked:false,following:false,followers:0,followingCount:0,likes:0}};mockHostGet.mockResolvedValue(mockTarget);mockTrack.mockResolvedValue(true);});
test('card impression records nothing; only successfully loaded full Host profile records Consumer visit',async()=>{const card=render(<Card host={mockTarget}/>);await flush();expect(mockTrack).not.toHaveBeenCalled();card.unmount();const props={route:{params:{userId:'h'}},navigation:{}};const screen=render(<Profile {...props}/>);await flush();expect(mockTrack).toHaveBeenCalledTimes(1);expect(mockTrack).toHaveBeenCalledWith('h');expect(screen.getByText('AMR-123456')).toBeTruthy();screen.rerender(<Profile {...props}/>);await flush();expect(mockTrack).toHaveBeenCalledTimes(1);screen.unmount();});
test('loading or failed full profile fetch never records a visitor',async()=>{let reject;mockHostGet.mockImplementation(()=>new Promise((_resolve,fail)=>{reject=fail;}));const screen=render(<Profile route={{params:{userId:'h'}}} navigation={{}}/>);await flush();expect(mockTrack).not.toHaveBeenCalled();await act(async()=>reject(new Error('unavailable')));await flush();expect(mockTrack).not.toHaveBeenCalled();screen.unmount();});
test('approved Host opening full Consumer profile tracks opposite direction and keeps full-profile Level',async()=>{mockUser={uid:'h',hostStatus:{isApproved:true}};mockConsumerGet.mockResolvedValue({uid:'c',amiraId:'AMR-654321',username:'Real Consumer',role:'consumer',hostStatus:{isApproved:false},hostProfile:{gallery:[],interests:[]}});const screen=render(<Profile route={{params:{userId:'c'}}} navigation={{}}/>);await flush();expect(mockConsumerGet).toHaveBeenCalledWith('c');expect(mockTrack).toHaveBeenCalledWith('c');expect(screen.getByLabelText('Amira Level 0')).toBeTruthy();expect(screen.getByText('AMR-654321')).toBeTruthy();screen.unmount();});
