import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Alert,FlatList,Modal,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {Coins,X} from 'lucide-react-native';
import {useNavigation} from '@react-navigation/native';
import {COLORS} from '../theme/COLORS';
import {giftService} from '../services/giftService';

const GiftTray=({visible,onClose,hostUid,source='messages',callId,onGiftSent})=>{
 const navigation=useNavigation(),[state,setState]=useState({loading:true,available:false,gifts:[]}),[sending,setSending]=useState(null),pending=useRef(null);
 useEffect(()=>{if(!visible)return;let active=true;setState({loading:true,available:false,gifts:[]});giftService.catalog().then(value=>{if(active)setState({loading:false,available:value.available===true,gifts:value.gifts||[]});}).catch(()=>{if(active)setState({loading:false,available:false,gifts:[]});});return()=>{active=false;};},[visible]);
 const send=async gift=>{if(sending||!hostUid)return;const request=pending.current?.giftId===gift.giftId?pending.current:{giftId:gift.giftId,requestId:giftService.requestId()};pending.current=request;setSending(gift.giftId);try{const result=await giftService.send({hostUid,giftId:gift.giftId,source,requestId:request.requestId,...(callId?{callId}:{})});pending.current=null;onGiftSent?.(gift,result);if(source!=='video_call')Alert.alert('Gift sent',`${gift.name} was sent.`);}catch(error){if(error.details?.reason==='insufficient_purchased_credits')Alert.alert('More purchased Credits needed','Bonus and legacy Credits cannot be used for Gifts. Recharge is not available yet.',[{text:'View Recharge',onPress:()=>{onClose();navigation.navigate('RechargeHub');}},{text:'Cancel',style:'cancel'}]);else if(error.details?.reason==='inactive_video_call')Alert.alert('Gift not sent','This Video Call is no longer active.');else Alert.alert('Gifts unavailable','Gifts are currently unavailable.');}finally{setSending(null);}};
 return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.overlay}><View style={styles.card}><View style={styles.header}><Text style={styles.title}>Send Gift</Text><TouchableOpacity accessibilityLabel="Close Gifts" onPress={onClose}><X color={COLORS.text}/></TouchableOpacity></View>{state.loading?<ActivityIndicator color={COLORS.primary}/>:!state.available||!state.gifts.length?<Text style={styles.empty}>Gifts are currently unavailable.</Text>:<FlatList data={state.gifts} keyExtractor={item=>item.giftId} numColumns={4} renderItem={({item})=><TouchableOpacity disabled={Boolean(sending)} style={styles.gift} onPress={()=>send(item)}><View style={styles.icon}><Text>{item.asset?.kind==='emoji'?item.asset.key:'🎁'}</Text></View><Text numberOfLines={1} style={styles.name}>{item.name}</Text><View style={styles.price}><Coins size={11} color="#B7791F"/><Text style={styles.priceText}>{item.priceCredits}</Text></View>{sending===item.giftId?<ActivityIndicator size="small" color={COLORS.primary}/>:null}</TouchableOpacity>}/>}</View></View></Modal>;
};
const styles=StyleSheet.create({overlay:{flex:1,justifyContent:'flex-end',backgroundColor:'rgba(0,0,0,.45)'},card:{minHeight:260,maxHeight:'55%',backgroundColor:'white',borderTopLeftRadius:24,borderTopRightRadius:24,padding:18},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:22},title:{fontSize:20,fontWeight:'900',color:COLORS.text},empty:{color:COLORS.textSecondary,textAlign:'center',marginTop:55,fontSize:16},gift:{width:'25%',alignItems:'center',padding:8,opacity:1},icon:{width:48,height:48,borderRadius:24,backgroundColor:'#FFF4E5',alignItems:'center',justifyContent:'center'},name:{fontSize:11,color:COLORS.text,marginTop:6},price:{flexDirection:'row',alignItems:'center',gap:3},priceText:{fontSize:11,fontWeight:'800',color:'#B7791F'}});
export default GiftTray;
