import React from 'react';
import {Image,StyleSheet,Text,TouchableOpacity,View} from 'react-native';
import {Video} from 'lucide-react-native';
import {getCountryByCode} from '../data/countries';
import {useRotatingHostPhoto} from '../hooks/useRotatingHostPhoto';
export const getHostCardLabels=host=>({showNew:false,showDemo:false,rate:Number.isSafeInteger(host.hostProfile?.videoRateCredits)&&host.hostProfile.videoRateCredits>0?`${host.hostProfile.videoRateCredits}/min`:'Rate unavailable'});
const HostCard=({host,onPress,onCallPress,compact=false,autoCycle=true})=>{
 const country=getCountryByCode(host.countryCode),{uri,onError}=useRotatingHostPhoto(host,autoCycle);
 const availability=['online','busy','offline'].includes(host.hostStatus?.availability)?host.hostStatus.availability:'offline';
 const rate=getHostCardLabels(host).rate,callAvailable=availability==='online'&&rate!=='Rate unavailable';
 return <TouchableOpacity style={[styles.card,compact&&styles.compact]} onPress={onPress} activeOpacity={0.9} accessibilityLabel={`Open ${host.username} profile`}>
 {uri?<Image source={{uri}} onError={onError} style={styles.photo}/>:<View style={[styles.photo,styles.placeholder]}><Text style={styles.letter}>{host.username?.[0]||'?'}</Text></View>}<View style={styles.scrim}/>
 <View style={[styles.online,{backgroundColor:availability==='busy'?'#92400E':'rgba(0,0,0,.65)'}]}><View style={[styles.dot,{backgroundColor:availability==='online'?'#22C55E':availability==='busy'?'#FBBF24':'#9CA3AF'}]}/><Text style={styles.onlineText}>{availability==='online'?'Online':availability==='busy'?'Busy':'Offline'}</Text></View>
 <View style={styles.info}><View style={styles.nameRow}><Text style={styles.name} numberOfLines={1}>{host.username}</Text>{country?.flag&&<Text>{country.flag}</Text>}</View><TouchableOpacity accessibilityLabel={`Video call ${host.username}, ${rate}`} accessibilityState={{disabled:!callAvailable}} disabled={!onCallPress||!callAvailable} onPress={onCallPress} style={styles.rate}><Video color="white" size={16}/><Text style={styles.rateText}>{rate}</Text></TouchableOpacity></View></TouchableOpacity>;
};
const styles=StyleSheet.create({card:{width:'48.5%',height:245,borderRadius:18,overflow:'hidden',backgroundColor:'#DDD',marginBottom:10},compact:{width:'100%',height:280},photo:{...StyleSheet.absoluteFillObject,width:'100%',height:'100%'},placeholder:{alignItems:'center',justifyContent:'center',backgroundColor:'#E9D5FF'},letter:{fontSize:50,fontWeight:'900',color:'#7C3AED'},scrim:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.15)'},storyRing:{position:'absolute',top:10,left:10,width:26,height:26,borderRadius:13,borderWidth:3,borderColor:'#FF2D55',padding:2},storyInner:{flex:1,borderRadius:10,borderWidth:1,borderColor:'white'},online:{position:'absolute',top:11,right:9,backgroundColor:'rgba(0,0,0,.55)',paddingHorizontal:7,paddingVertical:4,borderRadius:10,flexDirection:'row',alignItems:'center',gap:4},dot:{width:6,height:6,borderRadius:3,backgroundColor:'#22C55E'},onlineText:{color:'white',fontSize:8,fontWeight:'900'},badges:{position:'absolute',top:42,left:8,gap:4},newBadge:{backgroundColor:'#FF2D55',color:'white',fontSize:8,fontWeight:'900',paddingHorizontal:6,paddingVertical:3,borderRadius:7},demoBadge:{backgroundColor:'#7C3AED',color:'white',fontSize:8,fontWeight:'900',paddingHorizontal:6,paddingVertical:3,borderRadius:7},info:{position:'absolute',left:10,right:10,bottom:10},nameRow:{flexDirection:'row',alignItems:'center',gap:4},name:{color:'white',fontSize:17,fontWeight:'900',maxWidth:'88%'},country:{color:'white',fontSize:11,marginTop:2},rate:{alignSelf:'flex-start',flexDirection:'row',gap:3,alignItems:'center',marginTop:7,backgroundColor:'rgba(0,0,0,.52)',paddingHorizontal:7,paddingVertical:4,borderRadius:9},rateText:{color:'white',fontSize:9,fontWeight:'900'}});
export default HostCard;
