import {toDate} from './socialDomain';

const TERMINAL_WITHOUT_CONNECTION=new Set(['missed','rejected','failed','cancelled']);
export const callHistoryTimestampMs=value=>{const date=toDate(value);const ms=date?.getTime();return Number.isFinite(ms)&&ms>0?ms:null;};
export const callHistoryEventTimestamp=record=>record?.endedAt||record?.createdAt||null;
export const connectedDurationSeconds=record=>{const seconds=record?.durationSeconds;if(!Number.isSafeInteger(seconds)||seconds<0||TERMINAL_WITHOUT_CONNECTION.has(record?.status))return null;return callHistoryTimestampMs(record?.connectedAt)!==null&&['ended','connected'].includes(record?.status)?seconds:null;};
export const formatCallDuration=seconds=>{if(!Number.isSafeInteger(seconds)||seconds<0)return null;const hours=Math.floor(seconds/3600),minutes=Math.floor((seconds%3600)/60),remainder=seconds%60;return hours?`${hours}:${String(minutes).padStart(2,'0')}:${String(remainder).padStart(2,'0')}`:`${minutes}:${String(remainder).padStart(2,'0')}`;};
export const callHistoryStatusLabel=record=>record?.status==='rejected'&&record?.endReason==='declined'?'Declined video call':record?.status==='missed'&&['ring_timeout','no_answer'].includes(record?.endReason)?'Missed video call':'Video call';
export const formatCallHistoryTime=(value,nowMs=Date.now())=>{const timestamp=callHistoryTimestampMs(value);if(timestamp===null)return null;const minutes=Math.max(0,Math.floor((nowMs-timestamp)/60000));if(minutes===0)return 'Just now';if(minutes<60)return `${minutes}m ago`;if(minutes<1440)return `${Math.floor(minutes/60)}h ago`;if(minutes<2880)return 'Yesterday';if(minutes<10080)return `${Math.floor(minutes/1440)}d ago`;const date=new Date(timestamp);return date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:date.getFullYear()===new Date(nowMs).getFullYear()?undefined:'numeric'});};
export const normalizeCallHistoryRecord=(record,viewerUid)=>{const callId=record?.callId||record?.id,participants=record?.participantIds;if(typeof callId!=='string'||!Array.isArray(participants)||participants.length!==2||!participants.includes(viewerUid))return null;const counterpartUid=participants.find(uid=>uid!==viewerUid);if(typeof counterpartUid!=='string'||!counterpartUid)return null;const timestamp=callHistoryEventTimestamp(record),seconds=connectedDurationSeconds(record);return{id:callId,callId,counterpartUid,direction:record.callerId===viewerUid?'outgoing':record.receiverId===viewerUid?'incoming':null,label:callHistoryStatusLabel(record),durationSeconds:seconds,duration:formatCallDuration(seconds),timestamp,timestampMs:callHistoryTimestampMs(timestamp),source:typeof record.source==='string'?record.source:'direct'};};
export const normalizeCallHistoryRecords=(records,viewerUid)=>{const unique=new Map();for(const record of records||[]){const value=normalizeCallHistoryRecord(record,viewerUid);if(value&&!unique.has(value.callId))unique.set(value.callId,value);}return[...unique.values()].sort((a,b)=>(b.timestampMs||0)-(a.timestampMs||0)||a.callId.localeCompare(b.callId));};
