jest.mock('../../screens/main/MyLevelScreen',()=>()=>null);
import React from 'react';
import {render} from '@testing-library/react-native';
let mockUser;
jest.mock('../../context/UserContext',()=>({useUser:()=>({user:mockUser,loading:false})}));
jest.mock('../../context/MessageActivityContext',()=>({useMessageActivity:()=>({unread:0}),MessageActivityProvider:({children})=>children}));
jest.mock('../../services/socketService',()=>({socketService:{on:jest.fn(),off:jest.fn()}}));
jest.mock('@react-navigation/native',()=>({useNavigation:()=>({navigate:jest.fn()})}));
jest.mock('react-native-safe-area-context',()=>({SafeAreaProvider:({children})=>children}));
jest.mock('lucide-react-native',()=>Object.fromEntries(['Compass','HeartHandshake','Activity','MessageCircle','User'].map(key=>[key,()=>null])));
jest.mock('@react-navigation/bottom-tabs',()=>({createBottomTabNavigator:()=>({Navigator:({children,initialRouteName})=>{const {View}=require('react-native');return <View testID="tabs" accessibilityLabel={initialRouteName}>{children}</View>},Screen:({name})=>{const {Text}=require('react-native');return <Text>{name}</Text>}})}));
jest.mock('@react-navigation/native-stack',()=>({createNativeStackNavigator:()=>({Navigator:({children})=>children,Group:({children})=>children,Screen:({name})=>{const {Text}=require('react-native');return <Text>{name}</Text>}})}));
jest.mock('../../screens/host/HostActivityScreen',()=>()=>null);
jest.mock('../../screens/host/HostApplicationScreen',()=>()=>null);
jest.mock('../../screens/host/HostDashboardScreen',()=>()=>null);
jest.mock('../../screens/host/HostEarningsScreen',()=>()=>null);
jest.mock('../../screens/host/HostVisitorsScreen',()=>()=>null);
jest.mock('../../screens/main/BlockedUsersScreen',()=>()=>null);
jest.mock('../../screens/main/CallSummaryScreen',()=>()=>null);
jest.mock('../../screens/main/ChatDetailScreen',()=>()=>null);
jest.mock('../../screens/main/EditProfileScreen',()=>()=>null);
jest.mock('../../screens/main/FollowingScreen',()=>()=>null);
jest.mock('../../screens/main/GiftLedgerScreen',()=>()=>null);
jest.mock('../../screens/main/HelpSupportScreen',()=>()=>null);
jest.mock('../../screens/main/HomeScreen',()=>()=>null);
jest.mock('../../screens/main/InviteEarnScreen',()=>()=>null);
jest.mock('../../screens/main/LeaderboardScreen',()=>()=>null);
jest.mock('../../screens/main/MatchScreen',()=>()=>null);
jest.mock('../../screens/main/MessageHomeScreen',()=>()=>null);
jest.mock('../../screens/main/MomentsScreen',()=>()=>null);
jest.mock('../../screens/main/MyProfileScreen',()=>()=>null);
jest.mock('../../screens/main/PaymentMethodScreen',()=>()=>null);
jest.mock('../../screens/main/PaymentScreen',()=>()=>null);
jest.mock('../../screens/main/RechargeHubScreen',()=>()=>null);
jest.mock('../../screens/main/RewardsScreen',()=>()=>null);
jest.mock('../../screens/main/SettingsScreen',()=>()=>null);
jest.mock('../../screens/main/StoryViewerScreen',()=>()=>null);
jest.mock('../../screens/main/UserProfileScreen',()=>()=>null);
jest.mock('../../screens/main/VIPStoreScreen',()=>()=>null);
jest.mock('../../screens/main/VideoCallScreen',()=>()=>null);
jest.mock('../../screens/main/VipInfoScreen',()=>()=>null);
jest.mock('../../screens/main/WalletScreen',()=>()=>null);
jest.mock('../../screens/main/WhoViewedMeScreen',()=>()=>null);
jest.mock('../../screens/main/WithdrawalScreen',()=>()=>null);
jest.mock('../../screens/onboarding/BirthdaySetupScreen',()=>()=>null);
jest.mock('../../screens/onboarding/CountrySetupScreen',()=>()=>null);
jest.mock('../../screens/onboarding/GenderSetupScreen',()=>()=>null);
jest.mock('../../screens/onboarding/LoginScreen',()=>()=>null);
jest.mock('../../screens/onboarding/NameSetupScreen',()=>()=>null);
jest.mock('../../screens/onboarding/OTPScreen',()=>()=>null);
jest.mock('../../screens/onboarding/PhoneLoginScreen',()=>()=>null);
const Main=require('../MainTabNavigator').default,Root=require('../RootNavigator').default;
beforeEach(()=>{mockUser={uid:'p',username:'Person',dob:'1990-01-01',gender:'other',countryCode:'GH',role:'consumer',hostStatus:{isApproved:false}};});
test.each(['draft','submitted','pending','under_review'])('%s stays in Consumer tabs without Host privileges',status=>{
 mockUser.role='host';mockUser.hostStatus.verificationStatus=status;
 const screen=render(<Main/>);for(const text of ['Home','Match','Messages','Profile'])expect(screen.getByText(text)).toBeTruthy();for(const text of ['Connect','Activity','RoleSelection'])expect(screen.queryByText(text)).toBeNull();expect(screen.getByTestId('tabs').props.accessibilityLabel).toBe('Home');screen.unmount();
});
test('trusted approval replaces Consumer navigation with permanent Host destinations',()=>{
 const screen=render(<Main/>);mockUser={...mockUser,hostStatus:{isApproved:true}};screen.rerender(<Main/>);
 for(const text of ['Connect','Messages','Activity','Profile'])expect(screen.getByText(text)).toBeTruthy();for(const text of ['Home','Match','Switch to Consumer'])expect(screen.queryByText(text)).toBeNull();expect(screen.getByTestId('tabs').props.accessibilityLabel).toBe('Connect');screen.unmount();
});
test('approved Host stack excludes Consumer purchase/rewards/visitors and legacy withdrawals',()=>{
 mockUser.hostStatus.isApproved=true;const screen=render(<Root/>);
 for(const text of ['HostEarnings','FollowingList','HostVisitors'])expect(screen.getByText(text)).toBeTruthy();
 for(const text of ['MyLevel','Wallet','RechargeHub','VIPStore','Rewards','WhoViewedMe','VipInfo','Withdrawal','GiftLedger','HostApplication','RoleSelection'])expect(screen.queryByText(text)).toBeNull();screen.unmount();
});
test('pending applicant retains Consumer routes but cannot open earnings/Host visitors',()=>{
 mockUser.role='host';mockUser.hostStatus.verificationStatus='pending';const screen=render(<Root/>);
 for(const text of ['MyLevel','Rewards','WhoViewedMe','VipInfo','HostApplication','FollowingList'])expect(screen.getByText(text)).toBeTruthy();for(const text of ['HostEarnings','HostVisitors','RoleSelection'])expect(screen.queryByText(text)).toBeNull();screen.unmount();
});
